package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Advert generated by hbm2java
 */
public class Advert implements java.io.Serializable {

	private BigDecimal id;
	private String adpath;
	private String advertname;
	private double lat;
	private String city;
	private double lng;
	private Serializable uploadtime;

	public Advert() {
	}

	public Advert(BigDecimal id, String adpath, String advertname, double lat, String city, double lng) {
		this.id = id;
		this.adpath = adpath;
		this.advertname = advertname;
		this.lat = lat;
		this.city = city;
		this.lng = lng;
	}

	public Advert(BigDecimal id, String adpath, String advertname, double lat, String city, double lng,
			Serializable uploadtime) {
		this.id = id;
		this.adpath = adpath;
		this.advertname = advertname;
		this.lat = lat;
		this.city = city;
		this.lng = lng;
		this.uploadtime = uploadtime;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public String getAdpath() {
		return this.adpath;
	}

	public void setAdpath(String adpath) {
		this.adpath = adpath;
	}

	public String getAdvertname() {
		return this.advertname;
	}

	public void setAdvertname(String advertname) {
		this.advertname = advertname;
	}

	public double getLat() {
		return this.lat;
	}

	public void setLat(double lat) {
		this.lat = lat;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public double getLng() {
		return this.lng;
	}

	public void setLng(double lng) {
		this.lng = lng;
	}

	public Serializable getUploadtime() {
		return this.uploadtime;
	}

	public void setUploadtime(Serializable uploadtime) {
		this.uploadtime = uploadtime;
	}

}
