package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.math.BigDecimal;

import com.lmkj.util.dao.BaseEntity;
import com.lmkj.util.dao.PrimaryKey;

/**
 * Alarm generated by hbm2java
 */
public class Alarm extends BaseEntity<Alarm> {
	@PrimaryKey(IsAuto = true, Name = "id")
	private BigDecimal id;
	private String imei;
	private String alarmtype;
	private Serializable alarmtime;
	private Double longitude;
	private Double latitude;
	private String direction;
	private Double speed;
	private String locatetype;
	private String remark;
	private String isalarm;
	private String address;

	public Alarm() {
	}

	public Alarm(BigDecimal id, String imei) {
		this.id = id;
		this.imei = imei;
	}

	public Alarm(BigDecimal id, String imei, String alarmtype, Serializable alarmtime, Double longitude,
			Double latitude, String direction, Double speed, String locatetype, String remark, String isalarm,
			String address) {
		this.id = id;
		this.imei = imei;
		this.alarmtype = alarmtype;
		this.alarmtime = alarmtime;
		this.longitude = longitude;
		this.latitude = latitude;
		this.direction = direction;
		this.speed = speed;
		this.locatetype = locatetype;
		this.remark = remark;
		this.isalarm = isalarm;
		this.address = address;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public String getImei() {
		return this.imei;
	}

	public void setImei(String imei) {
		this.imei = imei;
	}

	public String getAlarmtype() {
		return this.alarmtype;
	}

	public void setAlarmtype(String alarmtype) {
		this.alarmtype = alarmtype;
	}

	public Serializable getAlarmtime() {
		return this.alarmtime;
	}

	public void setAlarmtime(Serializable alarmtime) {
		this.alarmtime = alarmtime;
	}

	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	public String getDirection() {
		return this.direction;
	}

	public void setDirection(String direction) {
		this.direction = direction;
	}

	public Double getSpeed() {
		return this.speed;
	}

	public void setSpeed(Double speed) {
		this.speed = speed;
	}

	public String getLocatetype() {
		return this.locatetype;
	}

	public void setLocatetype(String locatetype) {
		this.locatetype = locatetype;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getIsalarm() {
		return this.isalarm;
	}

	public void setIsalarm(String isalarm) {
		this.isalarm = isalarm;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

}
