package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Aliayorder generated by hbm2java
 */
public class Aliayorder implements java.io.Serializable {

	private BigDecimal oid;
	private BigDecimal orderstate;
	private BigDecimal uid;
	private double surplusmoney;
	private String tradesn;
	private Serializable tradetime;
	private Serializable cdate;
	private BigDecimal imonth;
	private BigDecimal iyear;
	private String imei;
	private BigDecimal tcid;
	private Serializable tcbdate;
	private Serializable tcedate;
	private String userorderid;

	public Aliayorder() {
	}

	public Aliayorder(BigDecimal oid, BigDecimal orderstate, BigDecimal uid, double surplusmoney, BigDecimal imonth,
			BigDecimal iyear, BigDecimal tcid, Serializable tcbdate, Serializable tcedate) {
		this.oid = oid;
		this.orderstate = orderstate;
		this.uid = uid;
		this.surplusmoney = surplusmoney;
		this.imonth = imonth;
		this.iyear = iyear;
		this.tcid = tcid;
		this.tcbdate = tcbdate;
		this.tcedate = tcedate;
	}

	public Aliayorder(BigDecimal oid, BigDecimal orderstate, BigDecimal uid, double surplusmoney, String tradesn,
			Serializable tradetime, Serializable cdate, BigDecimal imonth, BigDecimal iyear, String imei,
			BigDecimal tcid, Serializable tcbdate, Serializable tcedate, String userorderid) {
		this.oid = oid;
		this.orderstate = orderstate;
		this.uid = uid;
		this.surplusmoney = surplusmoney;
		this.tradesn = tradesn;
		this.tradetime = tradetime;
		this.cdate = cdate;
		this.imonth = imonth;
		this.iyear = iyear;
		this.imei = imei;
		this.tcid = tcid;
		this.tcbdate = tcbdate;
		this.tcedate = tcedate;
		this.userorderid = userorderid;
	}

	public BigDecimal getOid() {
		return this.oid;
	}

	public void setOid(BigDecimal oid) {
		this.oid = oid;
	}

	public BigDecimal getOrderstate() {
		return this.orderstate;
	}

	public void setOrderstate(BigDecimal orderstate) {
		this.orderstate = orderstate;
	}

	public BigDecimal getUid() {
		return this.uid;
	}

	public void setUid(BigDecimal uid) {
		this.uid = uid;
	}

	public double getSurplusmoney() {
		return this.surplusmoney;
	}

	public void setSurplusmoney(double surplusmoney) {
		this.surplusmoney = surplusmoney;
	}

	public String getTradesn() {
		return this.tradesn;
	}

	public void setTradesn(String tradesn) {
		this.tradesn = tradesn;
	}

	public Serializable getTradetime() {
		return this.tradetime;
	}

	public void setTradetime(Serializable tradetime) {
		this.tradetime = tradetime;
	}

	public Serializable getCdate() {
		return this.cdate;
	}

	public void setCdate(Serializable cdate) {
		this.cdate = cdate;
	}

	public BigDecimal getImonth() {
		return this.imonth;
	}

	public void setImonth(BigDecimal imonth) {
		this.imonth = imonth;
	}

	public BigDecimal getIyear() {
		return this.iyear;
	}

	public void setIyear(BigDecimal iyear) {
		this.iyear = iyear;
	}

	public String getImei() {
		return this.imei;
	}

	public void setImei(String imei) {
		this.imei = imei;
	}

	public BigDecimal getTcid() {
		return this.tcid;
	}

	public void setTcid(BigDecimal tcid) {
		this.tcid = tcid;
	}

	public Serializable getTcbdate() {
		return this.tcbdate;
	}

	public void setTcbdate(Serializable tcbdate) {
		this.tcbdate = tcbdate;
	}

	public Serializable getTcedate() {
		return this.tcedate;
	}

	public void setTcedate(Serializable tcedate) {
		this.tcedate = tcedate;
	}

	public String getUserorderid() {
		return this.userorderid;
	}

	public void setUserorderid(String userorderid) {
		this.userorderid = userorderid;
	}

}
