package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;

/**
 * Allotdevice generated by hbm2java
 */
public class Allotdevice implements java.io.Serializable {

	private BigDecimal id;
	private BigDecimal did;
	private BigDecimal cid;

	public Allotdevice() {
	}

	public Allotdevice(BigDecimal id, BigDecimal did, BigDecimal cid) {
		this.id = id;
		this.did = did;
		this.cid = cid;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public BigDecimal getDid() {
		return this.did;
	}

	public void setDid(BigDecimal did) {
		this.did = did;
	}

	public BigDecimal getCid() {
		return this.cid;
	}

	public void setCid(BigDecimal cid) {
		this.cid = cid;
	}

}
