package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Apilog generated by hbm2java
 */
public class Apilog implements java.io.Serializable {

	private BigDecimal id;
	private Serializable logdate;
	private String ip;
	private String useraccount;
	private String remark;
	private String udid;
	private String os;
	private String osversion;
	private String appversion;
	private String usersession;
	private String unique;
	private Serializable begintime;
	private String executetime;

	public Apilog() {
	}

	public Apilog(BigDecimal id) {
		this.id = id;
	}

	public Apilog(BigDecimal id, Serializable logdate, String ip, String useraccount, String remark, String udid,
			String os, String osversion, String appversion, String usersession, String unique, Serializable begintime,
			String executetime) {
		this.id = id;
		this.logdate = logdate;
		this.ip = ip;
		this.useraccount = useraccount;
		this.remark = remark;
		this.udid = udid;
		this.os = os;
		this.osversion = osversion;
		this.appversion = appversion;
		this.usersession = usersession;
		this.unique = unique;
		this.begintime = begintime;
		this.executetime = executetime;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public Serializable getLogdate() {
		return this.logdate;
	}

	public void setLogdate(Serializable logdate) {
		this.logdate = logdate;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public String getUseraccount() {
		return this.useraccount;
	}

	public void setUseraccount(String useraccount) {
		this.useraccount = useraccount;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getUdid() {
		return this.udid;
	}

	public void setUdid(String udid) {
		this.udid = udid;
	}

	public String getOs() {
		return this.os;
	}

	public void setOs(String os) {
		this.os = os;
	}

	public String getOsversion() {
		return this.osversion;
	}

	public void setOsversion(String osversion) {
		this.osversion = osversion;
	}

	public String getAppversion() {
		return this.appversion;
	}

	public void setAppversion(String appversion) {
		this.appversion = appversion;
	}

	public String getUsersession() {
		return this.usersession;
	}

	public void setUsersession(String usersession) {
		this.usersession = usersession;
	}

	public String getUnique() {
		return this.unique;
	}

	public void setUnique(String unique) {
		this.unique = unique;
	}

	public Serializable getBegintime() {
		return this.begintime;
	}

	public void setBegintime(Serializable begintime) {
		this.begintime = begintime;
	}

	public String getExecutetime() {
		return this.executetime;
	}

	public void setExecutetime(String executetime) {
		this.executetime = executetime;
	}

}
