package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Appdown generated by hbm2java
 */
public class Appdown implements java.io.Serializable {

	private BigDecimal serviceId;
	private String appname;
	private String filepath;
	private String filename;
	private BigDecimal filesize;
	private Serializable filecreatedate;
	private BigDecimal toland;
	private String appid;
	private String fileversion;
	private String devicemodel;
	private String remark;
	private BigDecimal istracklimit;
	private BigDecimal limittrack;
	private BigDecimal alarttack;
	private BigDecimal isnecessaryapp;
	private BigDecimal filetype;
	private String skinkey;

	public Appdown() {
	}

	public Appdown(BigDecimal serviceId, String appname, String filepath, String filename, BigDecimal filesize,
			Serializable filecreatedate, BigDecimal toland, String appid) {
		this.serviceId = serviceId;
		this.appname = appname;
		this.filepath = filepath;
		this.filename = filename;
		this.filesize = filesize;
		this.filecreatedate = filecreatedate;
		this.toland = toland;
		this.appid = appid;
	}

	public Appdown(BigDecimal serviceId, String appname, String filepath, String filename, BigDecimal filesize,
			Serializable filecreatedate, BigDecimal toland, String appid, String fileversion, String devicemodel,
			String remark, BigDecimal istracklimit, BigDecimal limittrack, BigDecimal alarttack,
			BigDecimal isnecessaryapp, BigDecimal filetype, String skinkey) {
		this.serviceId = serviceId;
		this.appname = appname;
		this.filepath = filepath;
		this.filename = filename;
		this.filesize = filesize;
		this.filecreatedate = filecreatedate;
		this.toland = toland;
		this.appid = appid;
		this.fileversion = fileversion;
		this.devicemodel = devicemodel;
		this.remark = remark;
		this.istracklimit = istracklimit;
		this.limittrack = limittrack;
		this.alarttack = alarttack;
		this.isnecessaryapp = isnecessaryapp;
		this.filetype = filetype;
		this.skinkey = skinkey;
	}

	public BigDecimal getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(BigDecimal serviceId) {
		this.serviceId = serviceId;
	}

	public String getAppname() {
		return this.appname;
	}

	public void setAppname(String appname) {
		this.appname = appname;
	}

	public String getFilepath() {
		return this.filepath;
	}

	public void setFilepath(String filepath) {
		this.filepath = filepath;
	}

	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	public BigDecimal getFilesize() {
		return this.filesize;
	}

	public void setFilesize(BigDecimal filesize) {
		this.filesize = filesize;
	}

	public Serializable getFilecreatedate() {
		return this.filecreatedate;
	}

	public void setFilecreatedate(Serializable filecreatedate) {
		this.filecreatedate = filecreatedate;
	}

	public BigDecimal getToland() {
		return this.toland;
	}

	public void setToland(BigDecimal toland) {
		this.toland = toland;
	}

	public String getAppid() {
		return this.appid;
	}

	public void setAppid(String appid) {
		this.appid = appid;
	}

	public String getFileversion() {
		return this.fileversion;
	}

	public void setFileversion(String fileversion) {
		this.fileversion = fileversion;
	}

	public String getDevicemodel() {
		return this.devicemodel;
	}

	public void setDevicemodel(String devicemodel) {
		this.devicemodel = devicemodel;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public BigDecimal getIstracklimit() {
		return this.istracklimit;
	}

	public void setIstracklimit(BigDecimal istracklimit) {
		this.istracklimit = istracklimit;
	}

	public BigDecimal getLimittrack() {
		return this.limittrack;
	}

	public void setLimittrack(BigDecimal limittrack) {
		this.limittrack = limittrack;
	}

	public BigDecimal getAlarttack() {
		return this.alarttack;
	}

	public void setAlarttack(BigDecimal alarttack) {
		this.alarttack = alarttack;
	}

	public BigDecimal getIsnecessaryapp() {
		return this.isnecessaryapp;
	}

	public void setIsnecessaryapp(BigDecimal isnecessaryapp) {
		this.isnecessaryapp = isnecessaryapp;
	}

	public BigDecimal getFiletype() {
		return this.filetype;
	}

	public void setFiletype(BigDecimal filetype) {
		this.filetype = filetype;
	}

	public String getSkinkey() {
		return this.skinkey;
	}

	public void setSkinkey(String skinkey) {
		this.skinkey = skinkey;
	}

}
