package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Apptrack generated by hbm2java
 */
public class Apptrack implements java.io.Serializable {

	private BigDecimal id;
	private String plateno;
	private String imei;
	private BigDecimal ayear;
	private BigDecimal amonth;
	private double ctrack;
	private double totaltrack;
	private Serializable rdate;

	public Apptrack() {
	}

	public Apptrack(BigDecimal id, String plateno, String imei, BigDecimal ayear, BigDecimal amonth, double ctrack,
			double totaltrack, Serializable rdate) {
		this.id = id;
		this.plateno = plateno;
		this.imei = imei;
		this.ayear = ayear;
		this.amonth = amonth;
		this.ctrack = ctrack;
		this.totaltrack = totaltrack;
		this.rdate = rdate;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public String getPlateno() {
		return this.plateno;
	}

	public void setPlateno(String plateno) {
		this.plateno = plateno;
	}

	public String getImei() {
		return this.imei;
	}

	public void setImei(String imei) {
		this.imei = imei;
	}

	public BigDecimal getAyear() {
		return this.ayear;
	}

	public void setAyear(BigDecimal ayear) {
		this.ayear = ayear;
	}

	public BigDecimal getAmonth() {
		return this.amonth;
	}

	public void setAmonth(BigDecimal amonth) {
		this.amonth = amonth;
	}

	public double getCtrack() {
		return this.ctrack;
	}

	public void setCtrack(double ctrack) {
		this.ctrack = ctrack;
	}

	public double getTotaltrack() {
		return this.totaltrack;
	}

	public void setTotaltrack(double totaltrack) {
		this.totaltrack = totaltrack;
	}

	public Serializable getRdate() {
		return this.rdate;
	}

	public void setRdate(Serializable rdate) {
		this.rdate = rdate;
	}

}
