package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

/**
 * BaseAppendpropertyinstance generated by hbm2java
 */
public class BaseAppendpropertyinstance implements java.io.Serializable {

	private String propertyinstanceId;
	private String propertyControlId;
	private String propertyinstanceValue;
	private String propertyinstanceKey;

	public BaseAppendpropertyinstance() {
	}

	public BaseAppendpropertyinstance(String propertyinstanceId) {
		this.propertyinstanceId = propertyinstanceId;
	}

	public BaseAppendpropertyinstance(String propertyinstanceId, String propertyControlId, String propertyinstanceValue,
			String propertyinstanceKey) {
		this.propertyinstanceId = propertyinstanceId;
		this.propertyControlId = propertyControlId;
		this.propertyinstanceValue = propertyinstanceValue;
		this.propertyinstanceKey = propertyinstanceKey;
	}

	public String getPropertyinstanceId() {
		return this.propertyinstanceId;
	}

	public void setPropertyinstanceId(String propertyinstanceId) {
		this.propertyinstanceId = propertyinstanceId;
	}

	public String getPropertyControlId() {
		return this.propertyControlId;
	}

	public void setPropertyControlId(String propertyControlId) {
		this.propertyControlId = propertyControlId;
	}

	public String getPropertyinstanceValue() {
		return this.propertyinstanceValue;
	}

	public void setPropertyinstanceValue(String propertyinstanceValue) {
		this.propertyinstanceValue = propertyinstanceValue;
	}

	public String getPropertyinstanceKey() {
		return this.propertyinstanceKey;
	}

	public void setPropertyinstanceKey(String propertyinstanceKey) {
		this.propertyinstanceKey = propertyinstanceKey;
	}

}
