package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;

/**
 * BaseRoleright generated by hbm2java
 */
public class BaseRoleright implements java.io.Serializable {

	private String rolerightId;
	private String rolesId;
	private String menuId;
	private Serializable createdate;
	private String createuserid;
	private String createusername;

	public BaseRoleright() {
	}

	public BaseRoleright(String rolerightId) {
		this.rolerightId = rolerightId;
	}

	public BaseRoleright(String rolerightId, String rolesId, String menuId, Serializable createdate,
			String createuserid, String createusername) {
		this.rolerightId = rolerightId;
		this.rolesId = rolesId;
		this.menuId = menuId;
		this.createdate = createdate;
		this.createuserid = createuserid;
		this.createusername = createusername;
	}

	public String getRolerightId() {
		return this.rolerightId;
	}

	public void setRolerightId(String rolerightId) {
		this.rolerightId = rolerightId;
	}

	public String getRolesId() {
		return this.rolesId;
	}

	public void setRolesId(String rolesId) {
		this.rolesId = rolesId;
	}

	public String getMenuId() {
		return this.menuId;
	}

	public void setMenuId(String menuId) {
		this.menuId = menuId;
	}

	public Serializable getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Serializable createdate) {
		this.createdate = createdate;
	}

	public String getCreateuserid() {
		return this.createuserid;
	}

	public void setCreateuserid(String createuserid) {
		this.createuserid = createuserid;
	}

	public String getCreateusername() {
		return this.createusername;
	}

	public void setCreateusername(String createusername) {
		this.createusername = createusername;
	}

}
