package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * BaseUsergroup generated by hbm2java
 */
public class BaseUsergroup implements java.io.Serializable {

	private String usergroupId;
	private String parentid;
	private String usergroupCode;
	private String usergroupName;
	private String usergroupRemark;
	private BigDecimal allowedit;
	private BigDecimal allowdelete;
	private BigDecimal sortcode;
	private BigDecimal deletemark;
	private Serializable createdate;
	private String createuserid;
	private String createusername;
	private Serializable modifydate;
	private String modifyuserid;
	private String modifyusername;
	private BigDecimal gid;

	public BaseUsergroup() {
	}

	public BaseUsergroup(String usergroupId, BigDecimal gid) {
		this.usergroupId = usergroupId;
		this.gid = gid;
	}

	public BaseUsergroup(String usergroupId, String parentid, String usergroupCode, String usergroupName,
			String usergroupRemark, BigDecimal allowedit, BigDecimal allowdelete, BigDecimal sortcode,
			BigDecimal deletemark, Serializable createdate, String createuserid, String createusername,
			Serializable modifydate, String modifyuserid, String modifyusername, BigDecimal gid) {
		this.usergroupId = usergroupId;
		this.parentid = parentid;
		this.usergroupCode = usergroupCode;
		this.usergroupName = usergroupName;
		this.usergroupRemark = usergroupRemark;
		this.allowedit = allowedit;
		this.allowdelete = allowdelete;
		this.sortcode = sortcode;
		this.deletemark = deletemark;
		this.createdate = createdate;
		this.createuserid = createuserid;
		this.createusername = createusername;
		this.modifydate = modifydate;
		this.modifyuserid = modifyuserid;
		this.modifyusername = modifyusername;
		this.gid = gid;
	}

	public String getUsergroupId() {
		return this.usergroupId;
	}

	public void setUsergroupId(String usergroupId) {
		this.usergroupId = usergroupId;
	}

	public String getParentid() {
		return this.parentid;
	}

	public void setParentid(String parentid) {
		this.parentid = parentid;
	}

	public String getUsergroupCode() {
		return this.usergroupCode;
	}

	public void setUsergroupCode(String usergroupCode) {
		this.usergroupCode = usergroupCode;
	}

	public String getUsergroupName() {
		return this.usergroupName;
	}

	public void setUsergroupName(String usergroupName) {
		this.usergroupName = usergroupName;
	}

	public String getUsergroupRemark() {
		return this.usergroupRemark;
	}

	public void setUsergroupRemark(String usergroupRemark) {
		this.usergroupRemark = usergroupRemark;
	}

	public BigDecimal getAllowedit() {
		return this.allowedit;
	}

	public void setAllowedit(BigDecimal allowedit) {
		this.allowedit = allowedit;
	}

	public BigDecimal getAllowdelete() {
		return this.allowdelete;
	}

	public void setAllowdelete(BigDecimal allowdelete) {
		this.allowdelete = allowdelete;
	}

	public BigDecimal getSortcode() {
		return this.sortcode;
	}

	public void setSortcode(BigDecimal sortcode) {
		this.sortcode = sortcode;
	}

	public BigDecimal getDeletemark() {
		return this.deletemark;
	}

	public void setDeletemark(BigDecimal deletemark) {
		this.deletemark = deletemark;
	}

	public Serializable getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Serializable createdate) {
		this.createdate = createdate;
	}

	public String getCreateuserid() {
		return this.createuserid;
	}

	public void setCreateuserid(String createuserid) {
		this.createuserid = createuserid;
	}

	public String getCreateusername() {
		return this.createusername;
	}

	public void setCreateusername(String createusername) {
		this.createusername = createusername;
	}

	public Serializable getModifydate() {
		return this.modifydate;
	}

	public void setModifydate(Serializable modifydate) {
		this.modifydate = modifydate;
	}

	public String getModifyuserid() {
		return this.modifyuserid;
	}

	public void setModifyuserid(String modifyuserid) {
		this.modifyuserid = modifyuserid;
	}

	public String getModifyusername() {
		return this.modifyusername;
	}

	public void setModifyusername(String modifyusername) {
		this.modifyusername = modifyusername;
	}

	public BigDecimal getGid() {
		return this.gid;
	}

	public void setGid(BigDecimal gid) {
		this.gid = gid;
	}

}
