package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * BaseUserinfousergroup generated by hbm2java
 */
public class BaseUserinfousergroup implements java.io.Serializable {

	private String userinfousergroupId;
	private String userId;
	private String usergroupId;
	private Serializable createdate;
	private String createuserid;
	private String createusername;
	private BigDecimal gid;

	public BaseUserinfousergroup() {
	}

	public BaseUserinfousergroup(String userinfousergroupId) {
		this.userinfousergroupId = userinfousergroupId;
	}

	public BaseUserinfousergroup(String userinfousergroupId, String userId, String usergroupId, Serializable createdate,
			String createuserid, String createusername, BigDecimal gid) {
		this.userinfousergroupId = userinfousergroupId;
		this.userId = userId;
		this.usergroupId = usergroupId;
		this.createdate = createdate;
		this.createuserid = createuserid;
		this.createusername = createusername;
		this.gid = gid;
	}

	public String getUserinfousergroupId() {
		return this.userinfousergroupId;
	}

	public void setUserinfousergroupId(String userinfousergroupId) {
		this.userinfousergroupId = userinfousergroupId;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getUsergroupId() {
		return this.usergroupId;
	}

	public void setUsergroupId(String usergroupId) {
		this.usergroupId = usergroupId;
	}

	public Serializable getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Serializable createdate) {
		this.createdate = createdate;
	}

	public String getCreateuserid() {
		return this.createuserid;
	}

	public void setCreateuserid(String createuserid) {
		this.createuserid = createuserid;
	}

	public String getCreateusername() {
		return this.createusername;
	}

	public void setCreateusername(String createusername) {
		this.createusername = createusername;
	}

	public BigDecimal getGid() {
		return this.gid;
	}

	public void setGid(BigDecimal gid) {
		this.gid = gid;
	}

}
