package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;

/**
 * BaseRecyclebin generated by hbm2java
 */
public class BaseRecyclebin implements java.io.Serializable {

	private String recyclebinId;
	private String recyclebinName;
	private String recyclebinDatabase;
	private String recyclebinTable;
	private String recyclebinFieldkey;
	private String recyclebinEventfield;
	private String recyclebinRemark;
	private Serializable createdate;
	private String createuserid;
	private String createusername;

	public BaseRecyclebin() {
	}

	public BaseRecyclebin(String recyclebinId) {
		this.recyclebinId = recyclebinId;
	}

	public BaseRecyclebin(String recyclebinId, String recyclebinName, String recyclebinDatabase, String recyclebinTable,
			String recyclebinFieldkey, String recyclebinEventfield, String recyclebinRemark, Serializable createdate,
			String createuserid, String createusername) {
		this.recyclebinId = recyclebinId;
		this.recyclebinName = recyclebinName;
		this.recyclebinDatabase = recyclebinDatabase;
		this.recyclebinTable = recyclebinTable;
		this.recyclebinFieldkey = recyclebinFieldkey;
		this.recyclebinEventfield = recyclebinEventfield;
		this.recyclebinRemark = recyclebinRemark;
		this.createdate = createdate;
		this.createuserid = createuserid;
		this.createusername = createusername;
	}

	public String getRecyclebinId() {
		return this.recyclebinId;
	}

	public void setRecyclebinId(String recyclebinId) {
		this.recyclebinId = recyclebinId;
	}

	public String getRecyclebinName() {
		return this.recyclebinName;
	}

	public void setRecyclebinName(String recyclebinName) {
		this.recyclebinName = recyclebinName;
	}

	public String getRecyclebinDatabase() {
		return this.recyclebinDatabase;
	}

	public void setRecyclebinDatabase(String recyclebinDatabase) {
		this.recyclebinDatabase = recyclebinDatabase;
	}

	public String getRecyclebinTable() {
		return this.recyclebinTable;
	}

	public void setRecyclebinTable(String recyclebinTable) {
		this.recyclebinTable = recyclebinTable;
	}

	public String getRecyclebinFieldkey() {
		return this.recyclebinFieldkey;
	}

	public void setRecyclebinFieldkey(String recyclebinFieldkey) {
		this.recyclebinFieldkey = recyclebinFieldkey;
	}

	public String getRecyclebinEventfield() {
		return this.recyclebinEventfield;
	}

	public void setRecyclebinEventfield(String recyclebinEventfield) {
		this.recyclebinEventfield = recyclebinEventfield;
	}

	public String getRecyclebinRemark() {
		return this.recyclebinRemark;
	}

	public void setRecyclebinRemark(String recyclebinRemark) {
		this.recyclebinRemark = recyclebinRemark;
	}

	public Serializable getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Serializable createdate) {
		this.createdate = createdate;
	}

	public String getCreateuserid() {
		return this.createuserid;
	}

	public void setCreateuserid(String createuserid) {
		this.createuserid = createuserid;
	}

	public String getCreateusername() {
		return this.createusername;
	}

	public void setCreateusername(String createusername) {
		this.createusername = createusername;
	}

}
