package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;

/**
 * BaseUserright generated by hbm2java
 */
public class BaseUserright implements java.io.Serializable {

	private String userrightId;
	private String userId;
	private String menuId;
	private Serializable createdate;
	private String createuserid;
	private String createusername;

	public BaseUserright() {
	}

	public BaseUserright(String userrightId) {
		this.userrightId = userrightId;
	}

	public BaseUserright(String userrightId, String userId, String menuId, Serializable createdate, String createuserid,
			String createusername) {
		this.userrightId = userrightId;
		this.userId = userId;
		this.menuId = menuId;
		this.createdate = createdate;
		this.createuserid = createuserid;
		this.createusername = createusername;
	}

	public String getUserrightId() {
		return this.userrightId;
	}

	public void setUserrightId(String userrightId) {
		this.userrightId = userrightId;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getMenuId() {
		return this.menuId;
	}

	public void setMenuId(String menuId) {
		this.menuId = menuId;
	}

	public Serializable getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Serializable createdate) {
		this.createdate = createdate;
	}

	public String getCreateuserid() {
		return this.createuserid;
	}

	public void setCreateuserid(String createuserid) {
		this.createuserid = createuserid;
	}

	public String getCreateusername() {
		return this.createusername;
	}

	public void setCreateusername(String createusername) {
		this.createusername = createusername;
	}

}
