package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;

/**
 * BaseUserinfoequipment generated by hbm2java
 */
public class BaseUserinfoequipment implements java.io.Serializable {

	private BigDecimal id;
	private String imei;
	private String userId;
	private String paypwd;

	public BaseUserinfoequipment() {
	}

	public BaseUserinfoequipment(BigDecimal id, String imei, String userId) {
		this.id = id;
		this.imei = imei;
		this.userId = userId;
	}

	public BaseUserinfoequipment(BigDecimal id, String imei, String userId, String paypwd) {
		this.id = id;
		this.imei = imei;
		this.userId = userId;
		this.paypwd = paypwd;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public String getImei() {
		return this.imei;
	}

	public void setImei(String imei) {
		this.imei = imei;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getPaypwd() {
		return this.paypwd;
	}

	public void setPaypwd(String paypwd) {
		this.paypwd = paypwd;
	}

}
