package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;

/**
 * BaseStafforganize generated by hbm2java
 */
public class BaseStafforganize implements java.io.Serializable {

	private String stafforganizeId;
	private String organizationId;
	private String userId;
	private Serializable createdate;
	private String createuserid;
	private String createusername;

	public BaseStafforganize() {
	}

	public BaseStafforganize(String stafforganizeId) {
		this.stafforganizeId = stafforganizeId;
	}

	public BaseStafforganize(String stafforganizeId, String organizationId, String userId, Serializable createdate,
			String createuserid, String createusername) {
		this.stafforganizeId = stafforganizeId;
		this.organizationId = organizationId;
		this.userId = userId;
		this.createdate = createdate;
		this.createuserid = createuserid;
		this.createusername = createusername;
	}

	public String getStafforganizeId() {
		return this.stafforganizeId;
	}

	public void setStafforganizeId(String stafforganizeId) {
		this.stafforganizeId = stafforganizeId;
	}

	public String getOrganizationId() {
		return this.organizationId;
	}

	public void setOrganizationId(String organizationId) {
		this.organizationId = organizationId;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public Serializable getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Serializable createdate) {
		this.createdate = createdate;
	}

	public String getCreateuserid() {
		return this.createuserid;
	}

	public void setCreateuserid(String createuserid) {
		this.createuserid = createuserid;
	}

	public String getCreateusername() {
		return this.createusername;
	}

	public void setCreateusername(String createusername) {
		this.createusername = createusername;
	}

}
