package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * BaseButton generated by hbm2java
 */
public class BaseButton implements java.io.Serializable {

	private String buttonId;
	private String buttonName;
	private String buttonTitle;
	private String buttonImg;
	private String buttonCode;
	private BigDecimal sortcode;
	private String buttonType;
	private String buttonRemak;
	private BigDecimal deletemark;
	private Serializable createdate;
	private String createuserid;
	private String createusername;
	private Serializable modifydate;
	private String modifyuserid;
	private String modifyusername;

	public BaseButton() {
	}

	public BaseButton(String buttonId) {
		this.buttonId = buttonId;
	}

	public BaseButton(String buttonId, String buttonName, String buttonTitle, String buttonImg, String buttonCode,
			BigDecimal sortcode, String buttonType, String buttonRemak, BigDecimal deletemark, Serializable createdate,
			String createuserid, String createusername, Serializable modifydate, String modifyuserid,
			String modifyusername) {
		this.buttonId = buttonId;
		this.buttonName = buttonName;
		this.buttonTitle = buttonTitle;
		this.buttonImg = buttonImg;
		this.buttonCode = buttonCode;
		this.sortcode = sortcode;
		this.buttonType = buttonType;
		this.buttonRemak = buttonRemak;
		this.deletemark = deletemark;
		this.createdate = createdate;
		this.createuserid = createuserid;
		this.createusername = createusername;
		this.modifydate = modifydate;
		this.modifyuserid = modifyuserid;
		this.modifyusername = modifyusername;
	}

	public String getButtonId() {
		return this.buttonId;
	}

	public void setButtonId(String buttonId) {
		this.buttonId = buttonId;
	}

	public String getButtonName() {
		return this.buttonName;
	}

	public void setButtonName(String buttonName) {
		this.buttonName = buttonName;
	}

	public String getButtonTitle() {
		return this.buttonTitle;
	}

	public void setButtonTitle(String buttonTitle) {
		this.buttonTitle = buttonTitle;
	}

	public String getButtonImg() {
		return this.buttonImg;
	}

	public void setButtonImg(String buttonImg) {
		this.buttonImg = buttonImg;
	}

	public String getButtonCode() {
		return this.buttonCode;
	}

	public void setButtonCode(String buttonCode) {
		this.buttonCode = buttonCode;
	}

	public BigDecimal getSortcode() {
		return this.sortcode;
	}

	public void setSortcode(BigDecimal sortcode) {
		this.sortcode = sortcode;
	}

	public String getButtonType() {
		return this.buttonType;
	}

	public void setButtonType(String buttonType) {
		this.buttonType = buttonType;
	}

	public String getButtonRemak() {
		return this.buttonRemak;
	}

	public void setButtonRemak(String buttonRemak) {
		this.buttonRemak = buttonRemak;
	}

	public BigDecimal getDeletemark() {
		return this.deletemark;
	}

	public void setDeletemark(BigDecimal deletemark) {
		this.deletemark = deletemark;
	}

	public Serializable getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Serializable createdate) {
		this.createdate = createdate;
	}

	public String getCreateuserid() {
		return this.createuserid;
	}

	public void setCreateuserid(String createuserid) {
		this.createuserid = createuserid;
	}

	public String getCreateusername() {
		return this.createusername;
	}

	public void setCreateusername(String createusername) {
		this.createusername = createusername;
	}

	public Serializable getModifydate() {
		return this.modifydate;
	}

	public void setModifydate(Serializable modifydate) {
		this.modifydate = modifydate;
	}

	public String getModifyuserid() {
		return this.modifyuserid;
	}

	public void setModifyuserid(String modifyuserid) {
		this.modifyuserid = modifyuserid;
	}

	public String getModifyusername() {
		return this.modifyusername;
	}

	public void setModifyusername(String modifyusername) {
		this.modifyusername = modifyusername;
	}

}
