package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * BaseOrganization generated by hbm2java
 */
public class BaseOrganization implements java.io.Serializable {

	private String organizationId;
	private String organizationCode;
	private String organizationName;
	private String organizationInnerphone;
	private String organizationOuterphone;
	private String organizationManager;
	private String organizationAssistantmanager;
	private String organizationFax;
	private String organizationZipcode;
	private String organizationAddress;
	private String parentid;
	private String organizationRemark;
	private BigDecimal sortcode;
	private BigDecimal deletemark;
	private Serializable createdate;
	private String createuserid;
	private String createusername;
	private Serializable modifydate;
	private String modifyuserid;
	private String modifyusername;

	public BaseOrganization() {
	}

	public BaseOrganization(String organizationId) {
		this.organizationId = organizationId;
	}

	public BaseOrganization(String organizationId, String organizationCode, String organizationName,
			String organizationInnerphone, String organizationOuterphone, String organizationManager,
			String organizationAssistantmanager, String organizationFax, String organizationZipcode,
			String organizationAddress, String parentid, String organizationRemark, BigDecimal sortcode,
			BigDecimal deletemark, Serializable createdate, String createuserid, String createusername,
			Serializable modifydate, String modifyuserid, String modifyusername) {
		this.organizationId = organizationId;
		this.organizationCode = organizationCode;
		this.organizationName = organizationName;
		this.organizationInnerphone = organizationInnerphone;
		this.organizationOuterphone = organizationOuterphone;
		this.organizationManager = organizationManager;
		this.organizationAssistantmanager = organizationAssistantmanager;
		this.organizationFax = organizationFax;
		this.organizationZipcode = organizationZipcode;
		this.organizationAddress = organizationAddress;
		this.parentid = parentid;
		this.organizationRemark = organizationRemark;
		this.sortcode = sortcode;
		this.deletemark = deletemark;
		this.createdate = createdate;
		this.createuserid = createuserid;
		this.createusername = createusername;
		this.modifydate = modifydate;
		this.modifyuserid = modifyuserid;
		this.modifyusername = modifyusername;
	}

	public String getOrganizationId() {
		return this.organizationId;
	}

	public void setOrganizationId(String organizationId) {
		this.organizationId = organizationId;
	}

	public String getOrganizationCode() {
		return this.organizationCode;
	}

	public void setOrganizationCode(String organizationCode) {
		this.organizationCode = organizationCode;
	}

	public String getOrganizationName() {
		return this.organizationName;
	}

	public void setOrganizationName(String organizationName) {
		this.organizationName = organizationName;
	}

	public String getOrganizationInnerphone() {
		return this.organizationInnerphone;
	}

	public void setOrganizationInnerphone(String organizationInnerphone) {
		this.organizationInnerphone = organizationInnerphone;
	}

	public String getOrganizationOuterphone() {
		return this.organizationOuterphone;
	}

	public void setOrganizationOuterphone(String organizationOuterphone) {
		this.organizationOuterphone = organizationOuterphone;
	}

	public String getOrganizationManager() {
		return this.organizationManager;
	}

	public void setOrganizationManager(String organizationManager) {
		this.organizationManager = organizationManager;
	}

	public String getOrganizationAssistantmanager() {
		return this.organizationAssistantmanager;
	}

	public void setOrganizationAssistantmanager(String organizationAssistantmanager) {
		this.organizationAssistantmanager = organizationAssistantmanager;
	}

	public String getOrganizationFax() {
		return this.organizationFax;
	}

	public void setOrganizationFax(String organizationFax) {
		this.organizationFax = organizationFax;
	}

	public String getOrganizationZipcode() {
		return this.organizationZipcode;
	}

	public void setOrganizationZipcode(String organizationZipcode) {
		this.organizationZipcode = organizationZipcode;
	}

	public String getOrganizationAddress() {
		return this.organizationAddress;
	}

	public void setOrganizationAddress(String organizationAddress) {
		this.organizationAddress = organizationAddress;
	}

	public String getParentid() {
		return this.parentid;
	}

	public void setParentid(String parentid) {
		this.parentid = parentid;
	}

	public String getOrganizationRemark() {
		return this.organizationRemark;
	}

	public void setOrganizationRemark(String organizationRemark) {
		this.organizationRemark = organizationRemark;
	}

	public BigDecimal getSortcode() {
		return this.sortcode;
	}

	public void setSortcode(BigDecimal sortcode) {
		this.sortcode = sortcode;
	}

	public BigDecimal getDeletemark() {
		return this.deletemark;
	}

	public void setDeletemark(BigDecimal deletemark) {
		this.deletemark = deletemark;
	}

	public Serializable getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Serializable createdate) {
		this.createdate = createdate;
	}

	public String getCreateuserid() {
		return this.createuserid;
	}

	public void setCreateuserid(String createuserid) {
		this.createuserid = createuserid;
	}

	public String getCreateusername() {
		return this.createusername;
	}

	public void setCreateusername(String createusername) {
		this.createusername = createusername;
	}

	public Serializable getModifydate() {
		return this.modifydate;
	}

	public void setModifydate(Serializable modifydate) {
		this.modifydate = modifydate;
	}

	public String getModifyuserid() {
		return this.modifyuserid;
	}

	public void setModifyuserid(String modifyuserid) {
		this.modifyuserid = modifyuserid;
	}

	public String getModifyusername() {
		return this.modifyusername;
	}

	public void setModifyusername(String modifyusername) {
		this.modifyusername = modifyusername;
	}

}
