package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * BaseSysmenu generated by hbm2java
 */
public class BaseSysmenu implements java.io.Serializable {

	private String menuId;
	private String parentid;
	private String menuName;
	private String menuTitle;
	private String menuImg;
	private BigDecimal menuType;
	private String navigateurl;
	private String target;
	private BigDecimal allowedit;
	private BigDecimal allowdelete;
	private BigDecimal sortcode;
	private BigDecimal deletemark;
	private Serializable createdate;
	private String createuserid;
	private String createusername;
	private Serializable modifydate;
	private String modifyuserid;
	private String modifyusername;

	public BaseSysmenu() {
	}

	public BaseSysmenu(String menuId, Serializable createdate) {
		this.menuId = menuId;
		this.createdate = createdate;
	}

	public BaseSysmenu(String menuId, String parentid, String menuName, String menuTitle, String menuImg,
			BigDecimal menuType, String navigateurl, String target, BigDecimal allowedit, BigDecimal allowdelete,
			BigDecimal sortcode, BigDecimal deletemark, Serializable createdate, String createuserid,
			String createusername, Serializable modifydate, String modifyuserid, String modifyusername) {
		this.menuId = menuId;
		this.parentid = parentid;
		this.menuName = menuName;
		this.menuTitle = menuTitle;
		this.menuImg = menuImg;
		this.menuType = menuType;
		this.navigateurl = navigateurl;
		this.target = target;
		this.allowedit = allowedit;
		this.allowdelete = allowdelete;
		this.sortcode = sortcode;
		this.deletemark = deletemark;
		this.createdate = createdate;
		this.createuserid = createuserid;
		this.createusername = createusername;
		this.modifydate = modifydate;
		this.modifyuserid = modifyuserid;
		this.modifyusername = modifyusername;
	}

	public String getMenuId() {
		return this.menuId;
	}

	public void setMenuId(String menuId) {
		this.menuId = menuId;
	}

	public String getParentid() {
		return this.parentid;
	}

	public void setParentid(String parentid) {
		this.parentid = parentid;
	}

	public String getMenuName() {
		return this.menuName;
	}

	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

	public String getMenuTitle() {
		return this.menuTitle;
	}

	public void setMenuTitle(String menuTitle) {
		this.menuTitle = menuTitle;
	}

	public String getMenuImg() {
		return this.menuImg;
	}

	public void setMenuImg(String menuImg) {
		this.menuImg = menuImg;
	}

	public BigDecimal getMenuType() {
		return this.menuType;
	}

	public void setMenuType(BigDecimal menuType) {
		this.menuType = menuType;
	}

	public String getNavigateurl() {
		return this.navigateurl;
	}

	public void setNavigateurl(String navigateurl) {
		this.navigateurl = navigateurl;
	}

	public String getTarget() {
		return this.target;
	}

	public void setTarget(String target) {
		this.target = target;
	}

	public BigDecimal getAllowedit() {
		return this.allowedit;
	}

	public void setAllowedit(BigDecimal allowedit) {
		this.allowedit = allowedit;
	}

	public BigDecimal getAllowdelete() {
		return this.allowdelete;
	}

	public void setAllowdelete(BigDecimal allowdelete) {
		this.allowdelete = allowdelete;
	}

	public BigDecimal getSortcode() {
		return this.sortcode;
	}

	public void setSortcode(BigDecimal sortcode) {
		this.sortcode = sortcode;
	}

	public BigDecimal getDeletemark() {
		return this.deletemark;
	}

	public void setDeletemark(BigDecimal deletemark) {
		this.deletemark = deletemark;
	}

	public Serializable getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Serializable createdate) {
		this.createdate = createdate;
	}

	public String getCreateuserid() {
		return this.createuserid;
	}

	public void setCreateuserid(String createuserid) {
		this.createuserid = createuserid;
	}

	public String getCreateusername() {
		return this.createusername;
	}

	public void setCreateusername(String createusername) {
		this.createusername = createusername;
	}

	public Serializable getModifydate() {
		return this.modifydate;
	}

	public void setModifydate(Serializable modifydate) {
		this.modifydate = modifydate;
	}

	public String getModifyuserid() {
		return this.modifyuserid;
	}

	public void setModifyuserid(String modifyuserid) {
		this.modifyuserid = modifyuserid;
	}

	public String getModifyusername() {
		return this.modifyusername;
	}

	public void setModifyusername(String modifyusername) {
		this.modifyusername = modifyusername;
	}

}
