package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * BaseRoles generated by hbm2java
 */
public class BaseRoles implements java.io.Serializable {

	private String rolesId;
	private String parentid;
	private String rolesName;
	private String roleRestriction;
	private String rolesRemark;
	private BigDecimal allowedit;
	private BigDecimal allowdelete;
	private BigDecimal sortcode;
	private BigDecimal deletemark;
	private Serializable createdate;
	private String createuserid;
	private String createusername;
	private Serializable modifydate;
	private String modifyuserid;
	private String modifyusername;

	public BaseRoles() {
	}

	public BaseRoles(String rolesId) {
		this.rolesId = rolesId;
	}

	public BaseRoles(String rolesId, String parentid, String rolesName, String roleRestriction, String rolesRemark,
			BigDecimal allowedit, BigDecimal allowdelete, BigDecimal sortcode, BigDecimal deletemark,
			Serializable createdate, String createuserid, String createusername, Serializable modifydate,
			String modifyuserid, String modifyusername) {
		this.rolesId = rolesId;
		this.parentid = parentid;
		this.rolesName = rolesName;
		this.roleRestriction = roleRestriction;
		this.rolesRemark = rolesRemark;
		this.allowedit = allowedit;
		this.allowdelete = allowdelete;
		this.sortcode = sortcode;
		this.deletemark = deletemark;
		this.createdate = createdate;
		this.createuserid = createuserid;
		this.createusername = createusername;
		this.modifydate = modifydate;
		this.modifyuserid = modifyuserid;
		this.modifyusername = modifyusername;
	}

	public String getRolesId() {
		return this.rolesId;
	}

	public void setRolesId(String rolesId) {
		this.rolesId = rolesId;
	}

	public String getParentid() {
		return this.parentid;
	}

	public void setParentid(String parentid) {
		this.parentid = parentid;
	}

	public String getRolesName() {
		return this.rolesName;
	}

	public void setRolesName(String rolesName) {
		this.rolesName = rolesName;
	}

	public String getRoleRestriction() {
		return this.roleRestriction;
	}

	public void setRoleRestriction(String roleRestriction) {
		this.roleRestriction = roleRestriction;
	}

	public String getRolesRemark() {
		return this.rolesRemark;
	}

	public void setRolesRemark(String rolesRemark) {
		this.rolesRemark = rolesRemark;
	}

	public BigDecimal getAllowedit() {
		return this.allowedit;
	}

	public void setAllowedit(BigDecimal allowedit) {
		this.allowedit = allowedit;
	}

	public BigDecimal getAllowdelete() {
		return this.allowdelete;
	}

	public void setAllowdelete(BigDecimal allowdelete) {
		this.allowdelete = allowdelete;
	}

	public BigDecimal getSortcode() {
		return this.sortcode;
	}

	public void setSortcode(BigDecimal sortcode) {
		this.sortcode = sortcode;
	}

	public BigDecimal getDeletemark() {
		return this.deletemark;
	}

	public void setDeletemark(BigDecimal deletemark) {
		this.deletemark = deletemark;
	}

	public Serializable getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Serializable createdate) {
		this.createdate = createdate;
	}

	public String getCreateuserid() {
		return this.createuserid;
	}

	public void setCreateuserid(String createuserid) {
		this.createuserid = createuserid;
	}

	public String getCreateusername() {
		return this.createusername;
	}

	public void setCreateusername(String createusername) {
		this.createusername = createusername;
	}

	public Serializable getModifydate() {
		return this.modifydate;
	}

	public void setModifydate(Serializable modifydate) {
		this.modifydate = modifydate;
	}

	public String getModifyuserid() {
		return this.modifyuserid;
	}

	public void setModifyuserid(String modifyuserid) {
		this.modifyuserid = modifyuserid;
	}

	public String getModifyusername() {
		return this.modifyusername;
	}

	public void setModifyusername(String modifyusername) {
		this.modifyusername = modifyusername;
	}

}
