package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.math.BigDecimal;

import com.lmkj.util.dao.BaseEntity;

/**
 * BaseUserinfo generated by hbm2java
 */
public class BaseUserinfo extends BaseEntity<BaseUserinfo> {

	private String userId;
	private String userCode;
	private String userAccount;
	private String userPwd;
	private String userName;
	private BigDecimal userSex;
	private String title;
	private String email;
	private String theme;
	private String question;
	private String answerquestion;
	private BigDecimal deletemark;
	private Serializable createdate;
	private String createuserid;
	private String createusername;
	private Serializable modifydate;
	private String modifyuserid;
	private String modifyusername;
	private String userRemark;
	private String comids;
	private BigDecimal usertype;
	private String pid;
	private String cid;
	private BigDecimal gid;
	private BigDecimal parentid;
	private BigDecimal uid;
	private String phone;
	private String fixedphone;
	private Double accountbalance;

	public BaseUserinfo() {
	}

	public BaseUserinfo(String userId, BigDecimal uid) {
		this.userId = userId;
		this.uid = uid;
	}

	public BaseUserinfo(String userId, String userCode, String userAccount, String userPwd, String userName,
			BigDecimal userSex, String title, String email, String theme, String question, String answerquestion,
			BigDecimal deletemark, Serializable createdate, String createuserid, String createusername,
			Serializable modifydate, String modifyuserid, String modifyusername, String userRemark, String comids,
			BigDecimal usertype, String pid, String cid, BigDecimal gid, BigDecimal parentid, BigDecimal uid,
			String phone, String fixedphone, Double accountbalance) {
		this.userId = userId;
		this.userCode = userCode;
		this.userAccount = userAccount;
		this.userPwd = userPwd;
		this.userName = userName;
		this.userSex = userSex;
		this.title = title;
		this.email = email;
		this.theme = theme;
		this.question = question;
		this.answerquestion = answerquestion;
		this.deletemark = deletemark;
		this.createdate = createdate;
		this.createuserid = createuserid;
		this.createusername = createusername;
		this.modifydate = modifydate;
		this.modifyuserid = modifyuserid;
		this.modifyusername = modifyusername;
		this.userRemark = userRemark;
		this.comids = comids;
		this.usertype = usertype;
		this.pid = pid;
		this.cid = cid;
		this.gid = gid;
		this.parentid = parentid;
		this.uid = uid;
		this.phone = phone;
		this.fixedphone = fixedphone;
		this.accountbalance = accountbalance;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getUserCode() {
		return this.userCode;
	}

	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}

	public String getUserAccount() {
		return this.userAccount;
	}

	public void setUserAccount(String userAccount) {
		this.userAccount = userAccount;
	}

	public String getUserPwd() {
		return this.userPwd;
	}

	public void setUserPwd(String userPwd) {
		this.userPwd = userPwd;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public BigDecimal getUserSex() {
		return this.userSex;
	}

	public void setUserSex(BigDecimal userSex) {
		this.userSex = userSex;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getTheme() {
		return this.theme;
	}

	public void setTheme(String theme) {
		this.theme = theme;
	}

	public String getQuestion() {
		return this.question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	public String getAnswerquestion() {
		return this.answerquestion;
	}

	public void setAnswerquestion(String answerquestion) {
		this.answerquestion = answerquestion;
	}

	public BigDecimal getDeletemark() {
		return this.deletemark;
	}

	public void setDeletemark(BigDecimal deletemark) {
		this.deletemark = deletemark;
	}

	public Serializable getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Serializable createdate) {
		this.createdate = createdate;
	}

	public String getCreateuserid() {
		return this.createuserid;
	}

	public void setCreateuserid(String createuserid) {
		this.createuserid = createuserid;
	}

	public String getCreateusername() {
		return this.createusername;
	}

	public void setCreateusername(String createusername) {
		this.createusername = createusername;
	}

	public Serializable getModifydate() {
		return this.modifydate;
	}

	public void setModifydate(Serializable modifydate) {
		this.modifydate = modifydate;
	}

	public String getModifyuserid() {
		return this.modifyuserid;
	}

	public void setModifyuserid(String modifyuserid) {
		this.modifyuserid = modifyuserid;
	}

	public String getModifyusername() {
		return this.modifyusername;
	}

	public void setModifyusername(String modifyusername) {
		this.modifyusername = modifyusername;
	}

	public String getUserRemark() {
		return this.userRemark;
	}

	public void setUserRemark(String userRemark) {
		this.userRemark = userRemark;
	}

	public String getComids() {
		return this.comids;
	}

	public void setComids(String comids) {
		this.comids = comids;
	}

	public BigDecimal getUsertype() {
		return this.usertype;
	}

	public void setUsertype(BigDecimal usertype) {
		this.usertype = usertype;
	}

	public String getPid() {
		return this.pid;
	}

	public void setPid(String pid) {
		this.pid = pid;
	}

	public String getCid() {
		return this.cid;
	}

	public void setCid(String cid) {
		this.cid = cid;
	}

	public BigDecimal getGid() {
		return this.gid;
	}

	public void setGid(BigDecimal gid) {
		this.gid = gid;
	}

	public BigDecimal getParentid() {
		return this.parentid;
	}

	public void setParentid(BigDecimal parentid) {
		this.parentid = parentid;
	}

	public BigDecimal getUid() {
		return this.uid;
	}

	public void setUid(BigDecimal uid) {
		this.uid = uid;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getFixedphone() {
		return this.fixedphone;
	}

	public void setFixedphone(String fixedphone) {
		this.fixedphone = fixedphone;
	}

	public Double getAccountbalance() {
		return this.accountbalance;
	}

	public void setAccountbalance(Double accountbalance) {
		this.accountbalance = accountbalance;
	}

}
