package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Basicdata generated by hbm2java
 */
public class Basicdata implements java.io.Serializable {

	private BigDecimal baseid;
	private String name;
	private String code;
	private String parent;
	private String meta;
	private Boolean deleted;
	private Serializable createdate;
	private BigDecimal tenantid;
	private String remark;

	public Basicdata() {
	}

	public Basicdata(BigDecimal baseid) {
		this.baseid = baseid;
	}

	public Basicdata(BigDecimal baseid, String name, String code, String parent, String meta, Boolean deleted,
			Serializable createdate, BigDecimal tenantid, String remark) {
		this.baseid = baseid;
		this.name = name;
		this.code = code;
		this.parent = parent;
		this.meta = meta;
		this.deleted = deleted;
		this.createdate = createdate;
		this.tenantid = tenantid;
		this.remark = remark;
	}

	public BigDecimal getBaseid() {
		return this.baseid;
	}

	public void setBaseid(BigDecimal baseid) {
		this.baseid = baseid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getParent() {
		return this.parent;
	}

	public void setParent(String parent) {
		this.parent = parent;
	}

	public String getMeta() {
		return this.meta;
	}

	public void setMeta(String meta) {
		this.meta = meta;
	}

	public Boolean getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

	public Serializable getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Serializable createdate) {
		this.createdate = createdate;
	}

	public BigDecimal getTenantid() {
		return this.tenantid;
	}

	public void setTenantid(BigDecimal tenantid) {
		this.tenantid = tenantid;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
