package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;

/**
 * BusrouteEnclosure generated by hbm2java
 */
public class BusrouteEnclosure implements java.io.Serializable {

	private BigDecimal enclosureid;
	private BigDecimal busrouteid;

	public BusrouteEnclosure() {
	}

	public BusrouteEnclosure(BigDecimal enclosureid, BigDecimal busrouteid) {
		this.enclosureid = enclosureid;
		this.busrouteid = busrouteid;
	}

	public BigDecimal getEnclosureid() {
		return this.enclosureid;
	}

	public void setEnclosureid(BigDecimal enclosureid) {
		this.enclosureid = enclosureid;
	}

	public BigDecimal getBusrouteid() {
		return this.busrouteid;
	}

	public void setBusrouteid(BigDecimal busrouteid) {
		this.busrouteid = busrouteid;
	}

}
