package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Busroute generated by hbm2java
 */
public class Busroute implements java.io.Serializable {

	private BigDecimal busrouteid;
	private String name;
	private String starttime;
	private String endtime;
	private Serializable createdate;
	private Boolean deleted;

	public Busroute() {
	}

	public Busroute(BigDecimal busrouteid) {
		this.busrouteid = busrouteid;
	}

	public Busroute(BigDecimal busrouteid, String name, String starttime, String endtime, Serializable createdate,
			Boolean deleted) {
		this.busrouteid = busrouteid;
		this.name = name;
		this.starttime = starttime;
		this.endtime = endtime;
		this.createdate = createdate;
		this.deleted = deleted;
	}

	public BigDecimal getBusrouteid() {
		return this.busrouteid;
	}

	public void setBusrouteid(BigDecimal busrouteid) {
		this.busrouteid = busrouteid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getStarttime() {
		return this.starttime;
	}

	public void setStarttime(String starttime) {
		this.starttime = starttime;
	}

	public String getEndtime() {
		return this.endtime;
	}

	public void setEndtime(String endtime) {
		this.endtime = endtime;
	}

	public Serializable getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Serializable createdate) {
		this.createdate = createdate;
	}

	public Boolean getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

}
