package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;

/**
 * Carbrand generated by hbm2java
 */
public class Carbrand implements java.io.Serializable {

	private BigDecimal brandid;
	private String brandname;

	public Carbrand() {
	}

	public Carbrand(BigDecimal brandid, String brandname) {
		this.brandid = brandid;
		this.brandname = brandname;
	}

	public BigDecimal getBrandid() {
		return this.brandid;
	}

	public void setBrandid(BigDecimal brandid) {
		this.brandid = brandid;
	}

	public String getBrandname() {
		return this.brandname;
	}

	public void setBrandname(String brandname) {
		this.brandname = brandname;
	}

}
