package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;

/**
 * Carmodel generated by hbm2java
 */
public class Carmodel implements java.io.Serializable {

	private BigDecimal modelid;
	private String modelname;
	private BigDecimal parentid;
	private String parentname;

	public Carmodel() {
	}

	public Carmodel(BigDecimal modelid, String modelname) {
		this.modelid = modelid;
		this.modelname = modelname;
	}

	public Carmodel(BigDecimal modelid, String modelname, BigDecimal parentid, String parentname) {
		this.modelid = modelid;
		this.modelname = modelname;
		this.parentid = parentid;
		this.parentname = parentname;
	}

	public BigDecimal getModelid() {
		return this.modelid;
	}

	public void setModelid(BigDecimal modelid) {
		this.modelid = modelid;
	}

	public String getModelname() {
		return this.modelname;
	}

	public void setModelname(String modelname) {
		this.modelname = modelname;
	}

	public BigDecimal getParentid() {
		return this.parentid;
	}

	public void setParentid(BigDecimal parentid) {
		this.parentid = parentid;
	}

	public String getParentname() {
		return this.parentname;
	}

	public void setParentname(String parentname) {
		this.parentname = parentname;
	}

}
