package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * Carrecord generated by hbm2java
 */
public class Carrecord implements java.io.Serializable {

	private BigDecimal fileid;
	private String filename;
	private BigDecimal finished;
	private String filepath;
	private String thumbnailpath;
	private String imei;
	private BigDecimal comid;
	private BigDecimal filesize;
	private String devicemodel;
	private BigDecimal isfinish;
	private String longitude;
	private String latitude;
	private String filetype;
	private Date cdate;
	private Date udate;
	private String plateno;
	private String skinkey;
	private String address;

	public Carrecord() {
	}

	public Carrecord(BigDecimal fileid, BigDecimal finished) {
		this.fileid = fileid;
		this.finished = finished;
	}

	public Carrecord(BigDecimal fileid, String filename, BigDecimal finished, String filepath, String thumbnailpath,
			String imei, BigDecimal comid, BigDecimal filesize, String devicemodel, BigDecimal isfinish,
			String longitude, String latitude, String filetype, Date cdate, Date udate, String plateno, String skinkey,
			String address) {
		this.fileid = fileid;
		this.filename = filename;
		this.finished = finished;
		this.filepath = filepath;
		this.thumbnailpath = thumbnailpath;
		this.imei = imei;
		this.comid = comid;
		this.filesize = filesize;
		this.devicemodel = devicemodel;
		this.isfinish = isfinish;
		this.longitude = longitude;
		this.latitude = latitude;
		this.filetype = filetype;
		this.cdate = cdate;
		this.udate = udate;
		this.plateno = plateno;
		this.skinkey = skinkey;
		this.address = address;
	}

	public BigDecimal getFileid() {
		return this.fileid;
	}

	public void setFileid(BigDecimal fileid) {
		this.fileid = fileid;
	}

	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	public BigDecimal getFinished() {
		return this.finished;
	}

	public void setFinished(BigDecimal finished) {
		this.finished = finished;
	}

	public String getFilepath() {
		return this.filepath;
	}

	public void setFilepath(String filepath) {
		this.filepath = filepath;
	}

	public String getThumbnailpath() {
		return this.thumbnailpath;
	}

	public void setThumbnailpath(String thumbnailpath) {
		this.thumbnailpath = thumbnailpath;
	}

	public String getImei() {
		return this.imei;
	}

	public void setImei(String imei) {
		this.imei = imei;
	}

	public BigDecimal getComid() {
		return this.comid;
	}

	public void setComid(BigDecimal comid) {
		this.comid = comid;
	}

	public BigDecimal getFilesize() {
		return this.filesize;
	}

	public void setFilesize(BigDecimal filesize) {
		this.filesize = filesize;
	}

	public String getDevicemodel() {
		return this.devicemodel;
	}

	public void setDevicemodel(String devicemodel) {
		this.devicemodel = devicemodel;
	}

	public BigDecimal getIsfinish() {
		return this.isfinish;
	}

	public void setIsfinish(BigDecimal isfinish) {
		this.isfinish = isfinish;
	}

	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	public String getFiletype() {
		return this.filetype;
	}

	public void setFiletype(String filetype) {
		this.filetype = filetype;
	}

	public Date getCdate() {
		return this.cdate;
	}

	public void setCdate(Date cdate) {
		this.cdate = cdate;
	}

	public Date getUdate() {
		return this.udate;
	}

	public void setUdate(Date udate) {
		this.udate = udate;
	}

	public String getPlateno() {
		return this.plateno;
	}

	public void setPlateno(String plateno) {
		this.plateno = plateno;
	}

	public String getSkinkey() {
		return this.skinkey;
	}

	public void setSkinkey(String skinkey) {
		this.skinkey = skinkey;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

}
