package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;

/**
 * Company generated by hbm2java
 */
public class Company implements java.io.Serializable {

	private BigDecimal id;
	private String comid;
	private String comname;
	private BigDecimal provinceid;
	private String cityid;
	private String commanager;
	private String comphone;
	private String address;
	private String remark;
	private BigDecimal sortcode;
	private BigDecimal parentid;
	private BigDecimal code;
	private BigDecimal authorizationcount;

	public Company() {
	}

	public Company(BigDecimal id, BigDecimal provinceid, String cityid, BigDecimal parentid) {
		this.id = id;
		this.provinceid = provinceid;
		this.cityid = cityid;
		this.parentid = parentid;
	}

	public Company(BigDecimal id, String comid, String comname, BigDecimal provinceid, String cityid, String commanager,
			String comphone, String address, String remark, BigDecimal sortcode, BigDecimal parentid, BigDecimal code,
			BigDecimal authorizationcount) {
		this.id = id;
		this.comid = comid;
		this.comname = comname;
		this.provinceid = provinceid;
		this.cityid = cityid;
		this.commanager = commanager;
		this.comphone = comphone;
		this.address = address;
		this.remark = remark;
		this.sortcode = sortcode;
		this.parentid = parentid;
		this.code = code;
		this.authorizationcount = authorizationcount;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public String getComid() {
		return this.comid;
	}

	public void setComid(String comid) {
		this.comid = comid;
	}

	public String getComname() {
		return this.comname;
	}

	public void setComname(String comname) {
		this.comname = comname;
	}

	public BigDecimal getProvinceid() {
		return this.provinceid;
	}

	public void setProvinceid(BigDecimal provinceid) {
		this.provinceid = provinceid;
	}

	public String getCityid() {
		return this.cityid;
	}

	public void setCityid(String cityid) {
		this.cityid = cityid;
	}

	public String getCommanager() {
		return this.commanager;
	}

	public void setCommanager(String commanager) {
		this.commanager = commanager;
	}

	public String getComphone() {
		return this.comphone;
	}

	public void setComphone(String comphone) {
		this.comphone = comphone;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public BigDecimal getSortcode() {
		return this.sortcode;
	}

	public void setSortcode(BigDecimal sortcode) {
		this.sortcode = sortcode;
	}

	public BigDecimal getParentid() {
		return this.parentid;
	}

	public void setParentid(BigDecimal parentid) {
		this.parentid = parentid;
	}

	public BigDecimal getCode() {
		return this.code;
	}

	public void setCode(BigDecimal code) {
		this.code = code;
	}

	public BigDecimal getAuthorizationcount() {
		return this.authorizationcount;
	}

	public void setAuthorizationcount(BigDecimal authorizationcount) {
		this.authorizationcount = authorizationcount;
	}

}
