package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Defense generated by hbm2java
 */
public class Defense implements java.io.Serializable {

	private BigDecimal id;
	private String plateno;
	private String imei;
	private String isband;
	private Double longitude;
	private Double latitude;
	private Double distance;
	private Serializable bandtime;

	public Defense() {
	}

	public Defense(BigDecimal id) {
		this.id = id;
	}

	public Defense(BigDecimal id, String plateno, String imei, String isband, Double longitude, Double latitude,
			Double distance, Serializable bandtime) {
		this.id = id;
		this.plateno = plateno;
		this.imei = imei;
		this.isband = isband;
		this.longitude = longitude;
		this.latitude = latitude;
		this.distance = distance;
		this.bandtime = bandtime;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public String getPlateno() {
		return this.plateno;
	}

	public void setPlateno(String plateno) {
		this.plateno = plateno;
	}

	public String getImei() {
		return this.imei;
	}

	public void setImei(String imei) {
		this.imei = imei;
	}

	public String getIsband() {
		return this.isband;
	}

	public void setIsband(String isband) {
		this.isband = isband;
	}

	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	public Double getDistance() {
		return this.distance;
	}

	public void setDistance(Double distance) {
		this.distance = distance;
	}

	public Serializable getBandtime() {
		return this.bandtime;
	}

	public void setBandtime(Serializable bandtime) {
		this.bandtime = bandtime;
	}

}
