package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Department generated by hbm2java
 */
public class Department implements java.io.Serializable {

	private BigDecimal depid;
	private String name;
	private BigDecimal parentid;
	private String memo;
	private String category;
	private Serializable createdate;
	private String owner;
	private BigDecimal tenantid;
	private Boolean deleted;

	public Department() {
	}

	public Department(BigDecimal depid) {
		this.depid = depid;
	}

	public Department(BigDecimal depid, String name, BigDecimal parentid, String memo, String category,
			Serializable createdate, String owner, BigDecimal tenantid, Boolean deleted) {
		this.depid = depid;
		this.name = name;
		this.parentid = parentid;
		this.memo = memo;
		this.category = category;
		this.createdate = createdate;
		this.owner = owner;
		this.tenantid = tenantid;
		this.deleted = deleted;
	}

	public BigDecimal getDepid() {
		return this.depid;
	}

	public void setDepid(BigDecimal depid) {
		this.depid = depid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public BigDecimal getParentid() {
		return this.parentid;
	}

	public void setParentid(BigDecimal parentid) {
		this.parentid = parentid;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public Serializable getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Serializable createdate) {
		this.createdate = createdate;
	}

	public String getOwner() {
		return this.owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}

	public BigDecimal getTenantid() {
		return this.tenantid;
	}

	public void setTenantid(BigDecimal tenantid) {
		this.tenantid = tenantid;
	}

	public Boolean getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

}
