package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;

/**
 * Deviceopenservice generated by hbm2java
 */
public class Deviceopenservice implements java.io.Serializable {

	private BigDecimal id;
	private String imei;
	private BigDecimal appid;

	public Deviceopenservice() {
	}

	public Deviceopenservice(BigDecimal id, String imei, BigDecimal appid) {
		this.id = id;
		this.imei = imei;
		this.appid = appid;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public String getImei() {
		return this.imei;
	}

	public void setImei(String imei) {
		this.imei = imei;
	}

	public BigDecimal getAppid() {
		return this.appid;
	}

	public void setAppid(BigDecimal appid) {
		this.appid = appid;
	}

}
