package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;

import com.lmkj.util.dao.BaseEntity;
import com.lmkj.util.dao.PrimaryKey;

/**
 * Deviceinfo generated by hbm2java
 */
public class Deviceinfo extends BaseEntity<Deviceinfo> {
	@PrimaryKey(IsAuto = true, Name = "id")
	private BigDecimal id;
	private String imei;
	private String plateno;
	private String simno;
	private String carphone;
	private Date cdate;
	private Date udate;
	private BigDecimal isinstall;
	private String tcpprotocol;
	private BigDecimal isallot;
	private BigDecimal isdel;
	private BigDecimal islocked;
	private String platform;
	private String password;
	private String platformbyplate;
	private String passwordbyplate;
	private BigDecimal totaltrack;
	private BigDecimal trackuser;
	private String flag;
	private String imsi;
	private BigDecimal isauthorization;
	private String guid;
	private String authorizationdate;
	private String invaliddate;
	private BigDecimal activation;

	public Deviceinfo() {
	}

	public Deviceinfo(BigDecimal id, String imei) {
		this.id = id;
		this.imei = imei;
	}

	public Deviceinfo(BigDecimal id, String imei, String plateno, String simno, String carphone, Date cdate, Date udate,
			BigDecimal isinstall, String tcpprotocol, BigDecimal isallot, BigDecimal isdel, BigDecimal islocked,
			String platform, String password, String platformbyplate, String passwordbyplate, BigDecimal totaltrack,
			BigDecimal trackuser, String flag, String imsi, BigDecimal isauthorization, String guid,
			String authorizationdate, String invaliddate, BigDecimal activation) {
		this.id = id;
		this.imei = imei;
		this.plateno = plateno;
		this.simno = simno;
		this.carphone = carphone;
		this.cdate = cdate;
		this.udate = udate;
		this.isinstall = isinstall;
		this.tcpprotocol = tcpprotocol;
		this.isallot = isallot;
		this.isdel = isdel;
		this.islocked = islocked;
		this.platform = platform;
		this.password = password;
		this.platformbyplate = platformbyplate;
		this.passwordbyplate = passwordbyplate;
		this.totaltrack = totaltrack;
		this.trackuser = trackuser;
		this.flag = flag;
		this.imsi = imsi;
		this.isauthorization = isauthorization;
		this.guid = guid;
		this.authorizationdate = authorizationdate;
		this.invaliddate = invaliddate;
		this.activation = activation;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public String getImei() {
		return this.imei;
	}

	public void setImei(String imei) {
		this.imei = imei;
	}

	public String getPlateno() {
		return this.plateno;
	}

	public void setPlateno(String plateno) {
		this.plateno = plateno;
	}

	public String getSimno() {
		return this.simno;
	}

	public void setSimno(String simno) {
		this.simno = simno;
	}

	public String getCarphone() {
		return this.carphone;
	}

	public void setCarphone(String carphone) {
		this.carphone = carphone;
	}

	public Date getCdate() {
		return this.cdate;
	}

	public void setCdate(Date cdate) {
		this.cdate = cdate;
	}

	public Date getUdate() {
		return this.udate;
	}

	public void setUdate(Date udate) {
		this.udate = udate;
	}

	public BigDecimal getIsinstall() {
		return this.isinstall;
	}

	public void setIsinstall(BigDecimal isinstall) {
		this.isinstall = isinstall;
	}

	public String getTcpprotocol() {
		return this.tcpprotocol;
	}

	public void setTcpprotocol(String tcpprotocol) {
		this.tcpprotocol = tcpprotocol;
	}

	public BigDecimal getIsallot() {
		return this.isallot;
	}

	public void setIsallot(BigDecimal isallot) {
		this.isallot = isallot;
	}

	public BigDecimal getIsdel() {
		return this.isdel;
	}

	public void setIsdel(BigDecimal isdel) {
		this.isdel = isdel;
	}

	public BigDecimal getIslocked() {
		return this.islocked;
	}

	public void setIslocked(BigDecimal islocked) {
		this.islocked = islocked;
	}

	public String getPlatform() {
		return this.platform;
	}

	public void setPlatform(String platform) {
		this.platform = platform;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPlatformbyplate() {
		return this.platformbyplate;
	}

	public void setPlatformbyplate(String platformbyplate) {
		this.platformbyplate = platformbyplate;
	}

	public String getPasswordbyplate() {
		return this.passwordbyplate;
	}

	public void setPasswordbyplate(String passwordbyplate) {
		this.passwordbyplate = passwordbyplate;
	}

	public BigDecimal getTotaltrack() {
		return this.totaltrack;
	}

	public void setTotaltrack(BigDecimal totaltrack) {
		this.totaltrack = totaltrack;
	}

	public BigDecimal getTrackuser() {
		return this.trackuser;
	}

	public void setTrackuser(BigDecimal trackuser) {
		this.trackuser = trackuser;
	}

	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	public String getImsi() {
		return this.imsi;
	}

	public void setImsi(String imsi) {
		this.imsi = imsi;
	}

	public BigDecimal getIsauthorization() {
		return this.isauthorization;
	}

	public void setIsauthorization(BigDecimal isauthorization) {
		this.isauthorization = isauthorization;
	}

	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	public String getAuthorizationdate() {
		return this.authorizationdate;
	}

	public void setAuthorizationdate(String authorizationdate) {
		this.authorizationdate = authorizationdate;
	}

	public String getInvaliddate() {
		return this.invaliddate;
	}

	public void setInvaliddate(String invaliddate) {
		this.invaliddate = invaliddate;
	}

	public BigDecimal getActivation() {
		return this.activation;
	}

	public void setActivation(BigDecimal activation) {
		this.activation = activation;
	}

}
