package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;

/**
 * Dicdb generated by hbm2java
 */
public class Dicdb implements java.io.Serializable {

	private BigDecimal id;
	private String dicid;
	private String dicname;
	private BigDecimal dictype;
	private String dicenname;

	public Dicdb() {
	}

	public Dicdb(BigDecimal id, String dicid, String dicname, BigDecimal dictype) {
		this.id = id;
		this.dicid = dicid;
		this.dicname = dicname;
		this.dictype = dictype;
	}

	public Dicdb(BigDecimal id, String dicid, String dicname, BigDecimal dictype, String dicenname) {
		this.id = id;
		this.dicid = dicid;
		this.dicname = dicname;
		this.dictype = dictype;
		this.dicenname = dicenname;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public String getDicid() {
		return this.dicid;
	}

	public void setDicid(String dicid) {
		this.dicid = dicid;
	}

	public String getDicname() {
		return this.dicname;
	}

	public void setDicname(String dicname) {
		this.dicname = dicname;
	}

	public BigDecimal getDictype() {
		return this.dictype;
	}

	public void setDictype(BigDecimal dictype) {
		this.dictype = dictype;
	}

	public String getDicenname() {
		return this.dicenname;
	}

	public void setDicenname(String dicenname) {
		this.dicenname = dicenname;
	}

}
