package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Blob;

/**
 * DistancecotInfo generated by hbm2java
 */
public class DistancecotInfo implements java.io.Serializable {

	private BigDecimal vehicleid;
	private Serializable createtime;
	private Double distancecot;
	private Double cotgas;
	private Blob staticDate;

	public DistancecotInfo() {
	}

	public DistancecotInfo(BigDecimal vehicleid) {
		this.vehicleid = vehicleid;
	}

	public DistancecotInfo(BigDecimal vehicleid, Serializable createtime, Double distancecot, Double cotgas,
			Blob staticDate) {
		this.vehicleid = vehicleid;
		this.createtime = createtime;
		this.distancecot = distancecot;
		this.cotgas = cotgas;
		this.staticDate = staticDate;
	}

	public BigDecimal getVehicleid() {
		return this.vehicleid;
	}

	public void setVehicleid(BigDecimal vehicleid) {
		this.vehicleid = vehicleid;
	}

	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	public Double getDistancecot() {
		return this.distancecot;
	}

	public void setDistancecot(Double distancecot) {
		this.distancecot = distancecot;
	}

	public Double getCotgas() {
		return this.cotgas;
	}

	public void setCotgas(Double cotgas) {
		this.cotgas = cotgas;
	}

	public Blob getStaticDate() {
		return this.staticDate;
	}

	public void setStaticDate(Blob staticDate) {
		this.staticDate = staticDate;
	}

}
