package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Enclosure generated by hbm2java
 */
public class Enclosure implements java.io.Serializable {

	private BigDecimal enclosureid;
	private BigDecimal tenantid;
	private String plateno;
	private String gpsid;
	private String points;
	private String name;
	private BigDecimal radius;
	private Boolean limitspeed;
	private Double maxspeed;
	private BigDecimal delay;
	private BigDecimal sn;
	private String enclosuretype;
	private String alarmtype;
	private Boolean gatherregion;
	private Boolean sensitiveregion;
	private BigDecimal gathernum;
	private Serializable createdate;
	private Boolean bytime;
	private Serializable startdate;
	private Serializable enddate;
	private Boolean deleted;

	public Enclosure() {
	}

	public Enclosure(BigDecimal enclosureid) {
		this.enclosureid = enclosureid;
	}

	public Enclosure(BigDecimal enclosureid, BigDecimal tenantid, String plateno, String gpsid, String points,
			String name, BigDecimal radius, Boolean limitspeed, Double maxspeed, BigDecimal delay, BigDecimal sn,
			String enclosuretype, String alarmtype, Boolean gatherregion, Boolean sensitiveregion, BigDecimal gathernum,
			Serializable createdate, Boolean bytime, Serializable startdate, Serializable enddate, Boolean deleted) {
		this.enclosureid = enclosureid;
		this.tenantid = tenantid;
		this.plateno = plateno;
		this.gpsid = gpsid;
		this.points = points;
		this.name = name;
		this.radius = radius;
		this.limitspeed = limitspeed;
		this.maxspeed = maxspeed;
		this.delay = delay;
		this.sn = sn;
		this.enclosuretype = enclosuretype;
		this.alarmtype = alarmtype;
		this.gatherregion = gatherregion;
		this.sensitiveregion = sensitiveregion;
		this.gathernum = gathernum;
		this.createdate = createdate;
		this.bytime = bytime;
		this.startdate = startdate;
		this.enddate = enddate;
		this.deleted = deleted;
	}

	public BigDecimal getEnclosureid() {
		return this.enclosureid;
	}

	public void setEnclosureid(BigDecimal enclosureid) {
		this.enclosureid = enclosureid;
	}

	public BigDecimal getTenantid() {
		return this.tenantid;
	}

	public void setTenantid(BigDecimal tenantid) {
		this.tenantid = tenantid;
	}

	public String getPlateno() {
		return this.plateno;
	}

	public void setPlateno(String plateno) {
		this.plateno = plateno;
	}

	public String getGpsid() {
		return this.gpsid;
	}

	public void setGpsid(String gpsid) {
		this.gpsid = gpsid;
	}

	public String getPoints() {
		return this.points;
	}

	public void setPoints(String points) {
		this.points = points;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public BigDecimal getRadius() {
		return this.radius;
	}

	public void setRadius(BigDecimal radius) {
		this.radius = radius;
	}

	public Boolean getLimitspeed() {
		return this.limitspeed;
	}

	public void setLimitspeed(Boolean limitspeed) {
		this.limitspeed = limitspeed;
	}

	public Double getMaxspeed() {
		return this.maxspeed;
	}

	public void setMaxspeed(Double maxspeed) {
		this.maxspeed = maxspeed;
	}

	public BigDecimal getDelay() {
		return this.delay;
	}

	public void setDelay(BigDecimal delay) {
		this.delay = delay;
	}

	public BigDecimal getSn() {
		return this.sn;
	}

	public void setSn(BigDecimal sn) {
		this.sn = sn;
	}

	public String getEnclosuretype() {
		return this.enclosuretype;
	}

	public void setEnclosuretype(String enclosuretype) {
		this.enclosuretype = enclosuretype;
	}

	public String getAlarmtype() {
		return this.alarmtype;
	}

	public void setAlarmtype(String alarmtype) {
		this.alarmtype = alarmtype;
	}

	public Boolean getGatherregion() {
		return this.gatherregion;
	}

	public void setGatherregion(Boolean gatherregion) {
		this.gatherregion = gatherregion;
	}

	public Boolean getSensitiveregion() {
		return this.sensitiveregion;
	}

	public void setSensitiveregion(Boolean sensitiveregion) {
		this.sensitiveregion = sensitiveregion;
	}

	public BigDecimal getGathernum() {
		return this.gathernum;
	}

	public void setGathernum(BigDecimal gathernum) {
		this.gathernum = gathernum;
	}

	public Serializable getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Serializable createdate) {
		this.createdate = createdate;
	}

	public Boolean getBytime() {
		return this.bytime;
	}

	public void setBytime(Boolean bytime) {
		this.bytime = bytime;
	}

	public Serializable getStartdate() {
		return this.startdate;
	}

	public void setStartdate(Serializable startdate) {
		this.startdate = startdate;
	}

	public Serializable getEnddate() {
		return this.enddate;
	}

	public void setEnddate(Serializable enddate) {
		this.enddate = enddate;
	}

	public Boolean getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

}
