package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;

/**
 * Equipmentfunction generated by hbm2java
 */
public class Equipmentfunction implements java.io.Serializable {

	private BigDecimal id;
	private String equipmentmodel;
	private String functionname;
	private String englishname;
	private String remark;

	public Equipmentfunction() {
	}

	public Equipmentfunction(BigDecimal id) {
		this.id = id;
	}

	public Equipmentfunction(BigDecimal id, String equipmentmodel, String functionname, String englishname,
			String remark) {
		this.id = id;
		this.equipmentmodel = equipmentmodel;
		this.functionname = functionname;
		this.englishname = englishname;
		this.remark = remark;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public String getEquipmentmodel() {
		return this.equipmentmodel;
	}

	public void setEquipmentmodel(String equipmentmodel) {
		this.equipmentmodel = equipmentmodel;
	}

	public String getFunctionname() {
		return this.functionname;
	}

	public void setFunctionname(String functionname) {
		this.functionname = functionname;
	}

	public String getEnglishname() {
		return this.englishname;
	}

	public void setEnglishname(String englishname) {
		this.englishname = englishname;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
