package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * Errorresult generated by hbm2java
 */
public class Errorresult implements java.io.Serializable {

	private BigDecimal id;
	private String imei;
	private String plateno;
	private Double longitude;
	private Double latitude;
	private Date sendtime;
	private Date updatetime;

	public Errorresult() {
	}

	public Errorresult(BigDecimal id) {
		this.id = id;
	}

	public Errorresult(BigDecimal id, String imei, String plateno, Double longitude, Double latitude, Date sendtime,
			Date updatetime) {
		this.id = id;
		this.imei = imei;
		this.plateno = plateno;
		this.longitude = longitude;
		this.latitude = latitude;
		this.sendtime = sendtime;
		this.updatetime = updatetime;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public String getImei() {
		return this.imei;
	}

	public void setImei(String imei) {
		this.imei = imei;
	}

	public String getPlateno() {
		return this.plateno;
	}

	public void setPlateno(String plateno) {
		this.plateno = plateno;
	}

	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	public Date getSendtime() {
		return this.sendtime;
	}

	public void setSendtime(Date sendtime) {
		this.sendtime = sendtime;
	}

	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

}
