package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Ewaybill generated by hbm2java
 */
public class Ewaybill implements java.io.Serializable {

	private BigDecimal billid;
	private String plateno;
	private String billcontent;
	private Serializable createdate;
	private Boolean deleted;
	private BigDecimal tenantid;

	public Ewaybill() {
	}

	public Ewaybill(BigDecimal billid) {
		this.billid = billid;
	}

	public Ewaybill(BigDecimal billid, String plateno, String billcontent, Serializable createdate, Boolean deleted,
			BigDecimal tenantid) {
		this.billid = billid;
		this.plateno = plateno;
		this.billcontent = billcontent;
		this.createdate = createdate;
		this.deleted = deleted;
		this.tenantid = tenantid;
	}

	public BigDecimal getBillid() {
		return this.billid;
	}

	public void setBillid(BigDecimal billid) {
		this.billid = billid;
	}

	public String getPlateno() {
		return this.plateno;
	}

	public void setPlateno(String plateno) {
		this.plateno = plateno;
	}

	public String getBillcontent() {
		return this.billcontent;
	}

	public void setBillcontent(String billcontent) {
		this.billcontent = billcontent;
	}

	public Serializable getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Serializable createdate) {
		this.createdate = createdate;
	}

	public Boolean getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

	public BigDecimal getTenantid() {
		return this.tenantid;
	}

	public void setTenantid(BigDecimal tenantid) {
		this.tenantid = tenantid;
	}

}
