package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Fuelconsumption generated by hbm2java
 */
public class Fuelconsumption implements java.io.Serializable {

	private BigDecimal id;
	private String plateno;
	private String intervaldescr;
	private Double hour;
	private Serializable staticdate;
	private BigDecimal intervaltype;
	private Double mileage;
	private Double oil;
	private Double oil1;
	private Double mileage1;
	private Double oil2;
	private Double mileage2;

	public Fuelconsumption() {
	}

	public Fuelconsumption(BigDecimal id) {
		this.id = id;
	}

	public Fuelconsumption(BigDecimal id, String plateno, String intervaldescr, Double hour, Serializable staticdate,
			BigDecimal intervaltype, Double mileage, Double oil, Double oil1, Double mileage1, Double oil2,
			Double mileage2) {
		this.id = id;
		this.plateno = plateno;
		this.intervaldescr = intervaldescr;
		this.hour = hour;
		this.staticdate = staticdate;
		this.intervaltype = intervaltype;
		this.mileage = mileage;
		this.oil = oil;
		this.oil1 = oil1;
		this.mileage1 = mileage1;
		this.oil2 = oil2;
		this.mileage2 = mileage2;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public String getPlateno() {
		return this.plateno;
	}

	public void setPlateno(String plateno) {
		this.plateno = plateno;
	}

	public String getIntervaldescr() {
		return this.intervaldescr;
	}

	public void setIntervaldescr(String intervaldescr) {
		this.intervaldescr = intervaldescr;
	}

	public Double getHour() {
		return this.hour;
	}

	public void setHour(Double hour) {
		this.hour = hour;
	}

	public Serializable getStaticdate() {
		return this.staticdate;
	}

	public void setStaticdate(Serializable staticdate) {
		this.staticdate = staticdate;
	}

	public BigDecimal getIntervaltype() {
		return this.intervaltype;
	}

	public void setIntervaltype(BigDecimal intervaltype) {
		this.intervaltype = intervaltype;
	}

	public Double getMileage() {
		return this.mileage;
	}

	public void setMileage(Double mileage) {
		this.mileage = mileage;
	}

	public Double getOil() {
		return this.oil;
	}

	public void setOil(Double oil) {
		this.oil = oil;
	}

	public Double getOil1() {
		return this.oil1;
	}

	public void setOil1(Double oil1) {
		this.oil1 = oil1;
	}

	public Double getMileage1() {
		return this.mileage1;
	}

	public void setMileage1(Double mileage1) {
		this.mileage1 = mileage1;
	}

	public Double getOil2() {
		return this.oil2;
	}

	public void setOil2(Double oil2) {
		this.oil2 = oil2;
	}

	public Double getMileage2() {
		return this.mileage2;
	}

	public void setMileage2(Double mileage2) {
		this.mileage2 = mileage2;
	}

}
