package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;

/**
 * FunctionRole generated by hbm2java
 */
public class FunctionRole implements java.io.Serializable {

	private BigDecimal roleid;
	private BigDecimal functionid;

	public FunctionRole() {
	}

	public FunctionRole(BigDecimal roleid, BigDecimal functionid) {
		this.roleid = roleid;
		this.functionid = functionid;
	}

	public BigDecimal getRoleid() {
		return this.roleid;
	}

	public void setRoleid(BigDecimal roleid) {
		this.roleid = roleid;
	}

	public BigDecimal getFunctionid() {
		return this.functionid;
	}

	public void setFunctionid(BigDecimal functionid) {
		this.functionid = functionid;
	}

}
