package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;

/**
 * FunctionModel generated by hbm2java
 */
public class FunctionModel implements java.io.Serializable {

	private BigDecimal functionid;
	private BigDecimal tenantid;
	private String name;
	private String code;
	private String url;
	private String icon;
	private String module;
	private BigDecimal sortid;
	private String flag;
	private String description;
	private Boolean deleted;

	public FunctionModel() {
	}

	public FunctionModel(BigDecimal functionid) {
		this.functionid = functionid;
	}

	public FunctionModel(BigDecimal functionid, BigDecimal tenantid, String name, String code, String url, String icon,
			String module, BigDecimal sortid, String flag, String description, Boolean deleted) {
		this.functionid = functionid;
		this.tenantid = tenantid;
		this.name = name;
		this.code = code;
		this.url = url;
		this.icon = icon;
		this.module = module;
		this.sortid = sortid;
		this.flag = flag;
		this.description = description;
		this.deleted = deleted;
	}

	public BigDecimal getFunctionid() {
		return this.functionid;
	}

	public void setFunctionid(BigDecimal functionid) {
		this.functionid = functionid;
	}

	public BigDecimal getTenantid() {
		return this.tenantid;
	}

	public void setTenantid(BigDecimal tenantid) {
		this.tenantid = tenantid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	public BigDecimal getSortid() {
		return this.sortid;
	}

	public void setSortid(BigDecimal sortid) {
		this.sortid = sortid;
	}

	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Boolean getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

}
