package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Geofence generated by hbm2java
 */
public class Geofence implements java.io.Serializable {

	private BigDecimal geofenceid;
	private String deviceid;
	private Double lat;
	private Double lng;
	private Double radius;
	private BigDecimal typeid;
	private String geofencename;
	private String remark;
	private Serializable cdate;

	public Geofence() {
	}

	public Geofence(BigDecimal geofenceid, String deviceid) {
		this.geofenceid = geofenceid;
		this.deviceid = deviceid;
	}

	public Geofence(BigDecimal geofenceid, String deviceid, Double lat, Double lng, Double radius, BigDecimal typeid,
			String geofencename, String remark, Serializable cdate) {
		this.geofenceid = geofenceid;
		this.deviceid = deviceid;
		this.lat = lat;
		this.lng = lng;
		this.radius = radius;
		this.typeid = typeid;
		this.geofencename = geofencename;
		this.remark = remark;
		this.cdate = cdate;
	}

	public BigDecimal getGeofenceid() {
		return this.geofenceid;
	}

	public void setGeofenceid(BigDecimal geofenceid) {
		this.geofenceid = geofenceid;
	}

	public String getDeviceid() {
		return this.deviceid;
	}

	public void setDeviceid(String deviceid) {
		this.deviceid = deviceid;
	}

	public Double getLat() {
		return this.lat;
	}

	public void setLat(Double lat) {
		this.lat = lat;
	}

	public Double getLng() {
		return this.lng;
	}

	public void setLng(Double lng) {
		this.lng = lng;
	}

	public Double getRadius() {
		return this.radius;
	}

	public void setRadius(Double radius) {
		this.radius = radius;
	}

	public BigDecimal getTypeid() {
		return this.typeid;
	}

	public void setTypeid(BigDecimal typeid) {
		this.typeid = typeid;
	}

	public String getGeofencename() {
		return this.geofencename;
	}

	public void setGeofencename(String geofencename) {
		this.geofencename = geofencename;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Serializable getCdate() {
		return this.cdate;
	}

	public void setCdate(Serializable cdate) {
		this.cdate = cdate;
	}

}
