package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Gpsmileage generated by hbm2java
 */
public class Gpsmileage implements java.io.Serializable {

	private BigDecimal id;
	private String plateno;
	private Double oillastcomp;
	private Double mileagelastcomp;
	private Serializable lastcomptime;
	private Double mileagelasthour;
	private Double oillasthour;
	private Double mileagelastday;
	private Double oillastday;
	private Double mileagelastmonth;
	private Double oillastmonth;
	private Serializable createdate;
	private Boolean deleted;

	public Gpsmileage() {
	}

	public Gpsmileage(BigDecimal id) {
		this.id = id;
	}

	public Gpsmileage(BigDecimal id, String plateno, Double oillastcomp, Double mileagelastcomp,
			Serializable lastcomptime, Double mileagelasthour, Double oillasthour, Double mileagelastday,
			Double oillastday, Double mileagelastmonth, Double oillastmonth, Serializable createdate, Boolean deleted) {
		this.id = id;
		this.plateno = plateno;
		this.oillastcomp = oillastcomp;
		this.mileagelastcomp = mileagelastcomp;
		this.lastcomptime = lastcomptime;
		this.mileagelasthour = mileagelasthour;
		this.oillasthour = oillasthour;
		this.mileagelastday = mileagelastday;
		this.oillastday = oillastday;
		this.mileagelastmonth = mileagelastmonth;
		this.oillastmonth = oillastmonth;
		this.createdate = createdate;
		this.deleted = deleted;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public String getPlateno() {
		return this.plateno;
	}

	public void setPlateno(String plateno) {
		this.plateno = plateno;
	}

	public Double getOillastcomp() {
		return this.oillastcomp;
	}

	public void setOillastcomp(Double oillastcomp) {
		this.oillastcomp = oillastcomp;
	}

	public Double getMileagelastcomp() {
		return this.mileagelastcomp;
	}

	public void setMileagelastcomp(Double mileagelastcomp) {
		this.mileagelastcomp = mileagelastcomp;
	}

	public Serializable getLastcomptime() {
		return this.lastcomptime;
	}

	public void setLastcomptime(Serializable lastcomptime) {
		this.lastcomptime = lastcomptime;
	}

	public Double getMileagelasthour() {
		return this.mileagelasthour;
	}

	public void setMileagelasthour(Double mileagelasthour) {
		this.mileagelasthour = mileagelasthour;
	}

	public Double getOillasthour() {
		return this.oillasthour;
	}

	public void setOillasthour(Double oillasthour) {
		this.oillasthour = oillasthour;
	}

	public Double getMileagelastday() {
		return this.mileagelastday;
	}

	public void setMileagelastday(Double mileagelastday) {
		this.mileagelastday = mileagelastday;
	}

	public Double getOillastday() {
		return this.oillastday;
	}

	public void setOillastday(Double oillastday) {
		this.oillastday = oillastday;
	}

	public Double getMileagelastmonth() {
		return this.mileagelastmonth;
	}

	public void setMileagelastmonth(Double mileagelastmonth) {
		this.mileagelastmonth = mileagelastmonth;
	}

	public Double getOillastmonth() {
		return this.oillastmonth;
	}

	public void setOillastmonth(Double oillastmonth) {
		this.oillastmonth = oillastmonth;
	}

	public Serializable getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Serializable createdate) {
		this.createdate = createdate;
	}

	public Boolean getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

}
