package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Gpsrealdata generated by hbm2java
 */
public class Gpsrealdata implements java.io.Serializable {

	private BigDecimal id;
	private BigDecimal vehicleid;
	private String plateno;
	private String orderid;
	private Serializable sendtime;
	private Double longitude;
	private Double latitude;
	private Double velocity;
	private Double direction;
	private String status;
	private Integer flowtype;
	private Boolean online;
	private String circuitstate;
	private String oilstate;
	private String statusb;
	private Boolean authorize;
	private String dvrstate;
	private Double mileage;
	private Double recordvelocity;
	private Boolean isvalid;
	private String simno;
	private Double oil;
	private String imei;
	private String protocoltype;
	private BigDecimal sensor0;
	private BigDecimal sensor1;
	private BigDecimal switch_;
	private BigDecimal switch1;
	private BigDecimal switch0;
	private String valvestate;
	private String doorstate;
	private String dvrstatus;
	private Serializable arrivedatetime;
	private BigDecimal meterstatus;
	private BigDecimal comid;
	private Double calcmileage;

	public Gpsrealdata() {
	}

	public Gpsrealdata(BigDecimal id) {
		this.id = id;
	}

	public Gpsrealdata(BigDecimal id, BigDecimal vehicleid, String plateno, String orderid, Serializable sendtime,
			Double longitude, Double latitude, Double velocity, Double direction, String status, Integer flowtype,
			Boolean online, String circuitstate, String oilstate, String statusb, Boolean authorize, String dvrstate,
			Double mileage, Double recordvelocity, Boolean isvalid, String simno, Double oil, String imei,
			String protocoltype, BigDecimal sensor0, BigDecimal sensor1, BigDecimal switch_, BigDecimal switch1,
			BigDecimal switch0, String valvestate, String doorstate, String dvrstatus, Serializable arrivedatetime,
			BigDecimal meterstatus, BigDecimal comid, Double calcmileage) {
		this.id = id;
		this.vehicleid = vehicleid;
		this.plateno = plateno;
		this.orderid = orderid;
		this.sendtime = sendtime;
		this.longitude = longitude;
		this.latitude = latitude;
		this.velocity = velocity;
		this.direction = direction;
		this.status = status;
		this.flowtype = flowtype;
		this.online = online;
		this.circuitstate = circuitstate;
		this.oilstate = oilstate;
		this.statusb = statusb;
		this.authorize = authorize;
		this.dvrstate = dvrstate;
		this.mileage = mileage;
		this.recordvelocity = recordvelocity;
		this.isvalid = isvalid;
		this.simno = simno;
		this.oil = oil;
		this.imei = imei;
		this.protocoltype = protocoltype;
		this.sensor0 = sensor0;
		this.sensor1 = sensor1;
		this.switch_ = switch_;
		this.switch1 = switch1;
		this.switch0 = switch0;
		this.valvestate = valvestate;
		this.doorstate = doorstate;
		this.dvrstatus = dvrstatus;
		this.arrivedatetime = arrivedatetime;
		this.meterstatus = meterstatus;
		this.comid = comid;
		this.calcmileage = calcmileage;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public BigDecimal getVehicleid() {
		return this.vehicleid;
	}

	public void setVehicleid(BigDecimal vehicleid) {
		this.vehicleid = vehicleid;
	}

	public String getPlateno() {
		return this.plateno;
	}

	public void setPlateno(String plateno) {
		this.plateno = plateno;
	}

	public String getOrderid() {
		return this.orderid;
	}

	public void setOrderid(String orderid) {
		this.orderid = orderid;
	}

	public Serializable getSendtime() {
		return this.sendtime;
	}

	public void setSendtime(Serializable sendtime) {
		this.sendtime = sendtime;
	}

	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	public Double getVelocity() {
		return this.velocity;
	}

	public void setVelocity(Double velocity) {
		this.velocity = velocity;
	}

	public Double getDirection() {
		return this.direction;
	}

	public void setDirection(Double direction) {
		this.direction = direction;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Integer getFlowtype() {
		return this.flowtype;
	}

	public void setFlowtype(Integer flowtype) {
		this.flowtype = flowtype;
	}

	public Boolean getOnline() {
		return this.online;
	}

	public void setOnline(Boolean online) {
		this.online = online;
	}

	public String getCircuitstate() {
		return this.circuitstate;
	}

	public void setCircuitstate(String circuitstate) {
		this.circuitstate = circuitstate;
	}

	public String getOilstate() {
		return this.oilstate;
	}

	public void setOilstate(String oilstate) {
		this.oilstate = oilstate;
	}

	public String getStatusb() {
		return this.statusb;
	}

	public void setStatusb(String statusb) {
		this.statusb = statusb;
	}

	public Boolean getAuthorize() {
		return this.authorize;
	}

	public void setAuthorize(Boolean authorize) {
		this.authorize = authorize;
	}

	public String getDvrstate() {
		return this.dvrstate;
	}

	public void setDvrstate(String dvrstate) {
		this.dvrstate = dvrstate;
	}

	public Double getMileage() {
		return this.mileage;
	}

	public void setMileage(Double mileage) {
		this.mileage = mileage;
	}

	public Double getRecordvelocity() {
		return this.recordvelocity;
	}

	public void setRecordvelocity(Double recordvelocity) {
		this.recordvelocity = recordvelocity;
	}

	public Boolean getIsvalid() {
		return this.isvalid;
	}

	public void setIsvalid(Boolean isvalid) {
		this.isvalid = isvalid;
	}

	public String getSimno() {
		return this.simno;
	}

	public void setSimno(String simno) {
		this.simno = simno;
	}

	public Double getOil() {
		return this.oil;
	}

	public void setOil(Double oil) {
		this.oil = oil;
	}

	public String getImei() {
		return this.imei;
	}

	public void setImei(String imei) {
		this.imei = imei;
	}

	public String getProtocoltype() {
		return this.protocoltype;
	}

	public void setProtocoltype(String protocoltype) {
		this.protocoltype = protocoltype;
	}

	public BigDecimal getSensor0() {
		return this.sensor0;
	}

	public void setSensor0(BigDecimal sensor0) {
		this.sensor0 = sensor0;
	}

	public BigDecimal getSensor1() {
		return this.sensor1;
	}

	public void setSensor1(BigDecimal sensor1) {
		this.sensor1 = sensor1;
	}

	public BigDecimal getSwitch_() {
		return this.switch_;
	}

	public void setSwitch_(BigDecimal switch_) {
		this.switch_ = switch_;
	}

	public BigDecimal getSwitch1() {
		return this.switch1;
	}

	public void setSwitch1(BigDecimal switch1) {
		this.switch1 = switch1;
	}

	public BigDecimal getSwitch0() {
		return this.switch0;
	}

	public void setSwitch0(BigDecimal switch0) {
		this.switch0 = switch0;
	}

	public String getValvestate() {
		return this.valvestate;
	}

	public void setValvestate(String valvestate) {
		this.valvestate = valvestate;
	}

	public String getDoorstate() {
		return this.doorstate;
	}

	public void setDoorstate(String doorstate) {
		this.doorstate = doorstate;
	}

	public String getDvrstatus() {
		return this.dvrstatus;
	}

	public void setDvrstatus(String dvrstatus) {
		this.dvrstatus = dvrstatus;
	}

	public Serializable getArrivedatetime() {
		return this.arrivedatetime;
	}

	public void setArrivedatetime(Serializable arrivedatetime) {
		this.arrivedatetime = arrivedatetime;
	}

	public BigDecimal getMeterstatus() {
		return this.meterstatus;
	}

	public void setMeterstatus(BigDecimal meterstatus) {
		this.meterstatus = meterstatus;
	}

	public BigDecimal getComid() {
		return this.comid;
	}

	public void setComid(BigDecimal comid) {
		this.comid = comid;
	}

	public Double getCalcmileage() {
		return this.calcmileage;
	}

	public void setCalcmileage(Double calcmileage) {
		this.calcmileage = calcmileage;
	}

}
