package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Huanxincommand generated by hbm2java
 */
public class Huanxincommand implements java.io.Serializable {

	private BigDecimal cmdid;
	private String gpsid;
	private String plateno;
	private String cmd;
	private String data;
	private Serializable createdate;
	private String fromuser;
	private String status;
	private String remark;
	private BigDecimal sn;
	private String touserhuanxin;
	private String touserweixin;
	private Serializable sendtime;
	private String title;
	private String messagetype;
	private String messagepushtype;
	private String apppackname;
	private String tonken;
	private String messagepushcontent;
	private BigDecimal key;
	private BigDecimal cmdstatus;
	private BigDecimal isremovealarm;

	public Huanxincommand() {
	}

	public Huanxincommand(BigDecimal cmdid, BigDecimal key) {
		this.cmdid = cmdid;
		this.key = key;
	}

	public Huanxincommand(BigDecimal cmdid, String gpsid, String plateno, String cmd, String data,
			Serializable createdate, String fromuser, String status, String remark, BigDecimal sn, String touserhuanxin,
			String touserweixin, Serializable sendtime, String title, String messagetype, String messagepushtype,
			String apppackname, String tonken, String messagepushcontent, BigDecimal key, BigDecimal cmdstatus,
			BigDecimal isremovealarm) {
		this.cmdid = cmdid;
		this.gpsid = gpsid;
		this.plateno = plateno;
		this.cmd = cmd;
		this.data = data;
		this.createdate = createdate;
		this.fromuser = fromuser;
		this.status = status;
		this.remark = remark;
		this.sn = sn;
		this.touserhuanxin = touserhuanxin;
		this.touserweixin = touserweixin;
		this.sendtime = sendtime;
		this.title = title;
		this.messagetype = messagetype;
		this.messagepushtype = messagepushtype;
		this.apppackname = apppackname;
		this.tonken = tonken;
		this.messagepushcontent = messagepushcontent;
		this.key = key;
		this.cmdstatus = cmdstatus;
		this.isremovealarm = isremovealarm;
	}

	public BigDecimal getCmdid() {
		return this.cmdid;
	}

	public void setCmdid(BigDecimal cmdid) {
		this.cmdid = cmdid;
	}

	public String getGpsid() {
		return this.gpsid;
	}

	public void setGpsid(String gpsid) {
		this.gpsid = gpsid;
	}

	public String getPlateno() {
		return this.plateno;
	}

	public void setPlateno(String plateno) {
		this.plateno = plateno;
	}

	public String getCmd() {
		return this.cmd;
	}

	public void setCmd(String cmd) {
		this.cmd = cmd;
	}

	public String getData() {
		return this.data;
	}

	public void setData(String data) {
		this.data = data;
	}

	public Serializable getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Serializable createdate) {
		this.createdate = createdate;
	}

	public String getFromuser() {
		return this.fromuser;
	}

	public void setFromuser(String fromuser) {
		this.fromuser = fromuser;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public BigDecimal getSn() {
		return this.sn;
	}

	public void setSn(BigDecimal sn) {
		this.sn = sn;
	}

	public String getTouserhuanxin() {
		return this.touserhuanxin;
	}

	public void setTouserhuanxin(String touserhuanxin) {
		this.touserhuanxin = touserhuanxin;
	}

	public String getTouserweixin() {
		return this.touserweixin;
	}

	public void setTouserweixin(String touserweixin) {
		this.touserweixin = touserweixin;
	}

	public Serializable getSendtime() {
		return this.sendtime;
	}

	public void setSendtime(Serializable sendtime) {
		this.sendtime = sendtime;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getMessagetype() {
		return this.messagetype;
	}

	public void setMessagetype(String messagetype) {
		this.messagetype = messagetype;
	}

	public String getMessagepushtype() {
		return this.messagepushtype;
	}

	public void setMessagepushtype(String messagepushtype) {
		this.messagepushtype = messagepushtype;
	}

	public String getApppackname() {
		return this.apppackname;
	}

	public void setApppackname(String apppackname) {
		this.apppackname = apppackname;
	}

	public String getTonken() {
		return this.tonken;
	}

	public void setTonken(String tonken) {
		this.tonken = tonken;
	}

	public String getMessagepushcontent() {
		return this.messagepushcontent;
	}

	public void setMessagepushcontent(String messagepushcontent) {
		this.messagepushcontent = messagepushcontent;
	}

	public BigDecimal getKey() {
		return this.key;
	}

	public void setKey(BigDecimal key) {
		this.key = key;
	}

	public BigDecimal getCmdstatus() {
		return this.cmdstatus;
	}

	public void setCmdstatus(BigDecimal cmdstatus) {
		this.cmdstatus = cmdstatus;
	}

	public BigDecimal getIsremovealarm() {
		return this.isremovealarm;
	}

	public void setIsremovealarm(BigDecimal isremovealarm) {
		this.isremovealarm = isremovealarm;
	}

}
