package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Information generated by hbm2java
 */
public class Information implements java.io.Serializable {

	private BigDecimal id;
	private String name;
	private String imei;
	private String openid;
	private Serializable bindtime;
	private String isband;

	public Information() {
	}

	public Information(BigDecimal id, String imei, String openid) {
		this.id = id;
		this.imei = imei;
		this.openid = openid;
	}

	public Information(BigDecimal id, String name, String imei, String openid, Serializable bindtime, String isband) {
		this.id = id;
		this.name = name;
		this.imei = imei;
		this.openid = openid;
		this.bindtime = bindtime;
		this.isband = isband;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getImei() {
		return this.imei;
	}

	public void setImei(String imei) {
		this.imei = imei;
	}

	public String getOpenid() {
		return this.openid;
	}

	public void setOpenid(String openid) {
		this.openid = openid;
	}

	public Serializable getBindtime() {
		return this.bindtime;
	}

	public void setBindtime(Serializable bindtime) {
		this.bindtime = bindtime;
	}

	public String getIsband() {
		return this.isband;
	}

	public void setIsband(String isband) {
		this.isband = isband;
	}

}
