package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Jt809command generated by hbm2java
 */
public class Jt809command implements java.io.Serializable {

	private BigDecimal cmdid;
	private String gpsid;
	private String plateno;
	private Integer platecolor;
	private BigDecimal cmd;
	private BigDecimal subcmd;
	private String data;
	private Serializable createdate;
	private String owner;
	private String status;
	private String remark;
	private BigDecimal sn;

	public Jt809command() {
	}

	public Jt809command(BigDecimal cmdid) {
		this.cmdid = cmdid;
	}

	public Jt809command(BigDecimal cmdid, String gpsid, String plateno, Integer platecolor, BigDecimal cmd,
			BigDecimal subcmd, String data, Serializable createdate, String owner, String status, String remark,
			BigDecimal sn) {
		this.cmdid = cmdid;
		this.gpsid = gpsid;
		this.plateno = plateno;
		this.platecolor = platecolor;
		this.cmd = cmd;
		this.subcmd = subcmd;
		this.data = data;
		this.createdate = createdate;
		this.owner = owner;
		this.status = status;
		this.remark = remark;
		this.sn = sn;
	}

	public BigDecimal getCmdid() {
		return this.cmdid;
	}

	public void setCmdid(BigDecimal cmdid) {
		this.cmdid = cmdid;
	}

	public String getGpsid() {
		return this.gpsid;
	}

	public void setGpsid(String gpsid) {
		this.gpsid = gpsid;
	}

	public String getPlateno() {
		return this.plateno;
	}

	public void setPlateno(String plateno) {
		this.plateno = plateno;
	}

	public Integer getPlatecolor() {
		return this.platecolor;
	}

	public void setPlatecolor(Integer platecolor) {
		this.platecolor = platecolor;
	}

	public BigDecimal getCmd() {
		return this.cmd;
	}

	public void setCmd(BigDecimal cmd) {
		this.cmd = cmd;
	}

	public BigDecimal getSubcmd() {
		return this.subcmd;
	}

	public void setSubcmd(BigDecimal subcmd) {
		this.subcmd = subcmd;
	}

	public String getData() {
		return this.data;
	}

	public void setData(String data) {
		this.data = data;
	}

	public Serializable getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Serializable createdate) {
		this.createdate = createdate;
	}

	public String getOwner() {
		return this.owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public BigDecimal getSn() {
		return this.sn;
	}

	public void setSn(BigDecimal sn) {
		this.sn = sn;
	}

}
