package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

/**
 * Leauditcollectconfigvars generated by hbm2java
 */
public class Leauditcollectconfigvars implements java.io.Serializable {

	private String optionname;
	private String value;

	public Leauditcollectconfigvars() {
	}

	public Leauditcollectconfigvars(String optionname) {
		this.optionname = optionname;
	}

	public Leauditcollectconfigvars(String optionname, String value) {
		this.optionname = optionname;
		this.value = value;
	}

	public String getOptionname() {
		return this.optionname;
	}

	public void setOptionname(String optionname) {
		this.optionname = optionname;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
