package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;

/**
 * Leauditcollectdatabases generated by hbm2java
 */
public class Leauditcollectdatabases implements java.io.Serializable {

	private BigDecimal databaseid;
	private String databasename;
	private String databaselogbackuppool;
	private BigDecimal backupppid;
	private String repositoryhostname;
	private BigDecimal repositoryhostport;
	private String globalrepositoryname;
	private char auditon;
	private String opfilter;

	public Leauditcollectdatabases() {
	}

	public Leauditcollectdatabases(BigDecimal databaseid, char auditon) {
		this.databaseid = databaseid;
		this.auditon = auditon;
	}

	public Leauditcollectdatabases(BigDecimal databaseid, String databasename, String databaselogbackuppool,
			BigDecimal backupppid, String repositoryhostname, BigDecimal repositoryhostport,
			String globalrepositoryname, char auditon, String opfilter) {
		this.databaseid = databaseid;
		this.databasename = databasename;
		this.databaselogbackuppool = databaselogbackuppool;
		this.backupppid = backupppid;
		this.repositoryhostname = repositoryhostname;
		this.repositoryhostport = repositoryhostport;
		this.globalrepositoryname = globalrepositoryname;
		this.auditon = auditon;
		this.opfilter = opfilter;
	}

	public BigDecimal getDatabaseid() {
		return this.databaseid;
	}

	public void setDatabaseid(BigDecimal databaseid) {
		this.databaseid = databaseid;
	}

	public String getDatabasename() {
		return this.databasename;
	}

	public void setDatabasename(String databasename) {
		this.databasename = databasename;
	}

	public String getDatabaselogbackuppool() {
		return this.databaselogbackuppool;
	}

	public void setDatabaselogbackuppool(String databaselogbackuppool) {
		this.databaselogbackuppool = databaselogbackuppool;
	}

	public BigDecimal getBackupppid() {
		return this.backupppid;
	}

	public void setBackupppid(BigDecimal backupppid) {
		this.backupppid = backupppid;
	}

	public String getRepositoryhostname() {
		return this.repositoryhostname;
	}

	public void setRepositoryhostname(String repositoryhostname) {
		this.repositoryhostname = repositoryhostname;
	}

	public BigDecimal getRepositoryhostport() {
		return this.repositoryhostport;
	}

	public void setRepositoryhostport(BigDecimal repositoryhostport) {
		this.repositoryhostport = repositoryhostport;
	}

	public String getGlobalrepositoryname() {
		return this.globalrepositoryname;
	}

	public void setGlobalrepositoryname(String globalrepositoryname) {
		this.globalrepositoryname = globalrepositoryname;
	}

	public char getAuditon() {
		return this.auditon;
	}

	public void setAuditon(char auditon) {
		this.auditon = auditon;
	}

	public String getOpfilter() {
		return this.opfilter;
	}

	public void setOpfilter(String opfilter) {
		this.opfilter = opfilter;
	}

}
