package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;

/**
 * Leauditcollectnotification generated by hbm2java
 */
public class Leauditcollectnotification implements java.io.Serializable {

	private BigDecimal notificationid;
	private BigDecimal type;
	private String param1;
	private String param2;

	public Leauditcollectnotification() {
	}

	public Leauditcollectnotification(BigDecimal notificationid, BigDecimal type) {
		this.notificationid = notificationid;
		this.type = type;
	}

	public Leauditcollectnotification(BigDecimal notificationid, BigDecimal type, String param1, String param2) {
		this.notificationid = notificationid;
		this.type = type;
		this.param1 = param1;
		this.param2 = param2;
	}

	public BigDecimal getNotificationid() {
		return this.notificationid;
	}

	public void setNotificationid(BigDecimal notificationid) {
		this.notificationid = notificationid;
	}

	public BigDecimal getType() {
		return this.type;
	}

	public void setType(BigDecimal type) {
		this.type = type;
	}

	public String getParam1() {
		return this.param1;
	}

	public void setParam1(String param1) {
		this.param1 = param1;
	}

	public String getParam2() {
		return this.param2;
	}

	public void setParam2(String param2) {
		this.param2 = param2;
	}

}
