package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Maplayer generated by hbm2java
 */
public class Maplayer implements java.io.Serializable {

	private BigDecimal layerid;
	private String name;
	private Boolean visible;
	private Boolean animated;
	private String icon;
	private BigDecimal tenantid;
	private BigDecimal maxiconzoom;
	private BigDecimal maxlabelzoom;
	private BigDecimal miniconzoom;
	private BigDecimal minlabelzoom;
	private Serializable createdate;
	private String creator;
	private String forecolor;
	private Boolean deleted;

	public Maplayer() {
	}

	public Maplayer(BigDecimal layerid) {
		this.layerid = layerid;
	}

	public Maplayer(BigDecimal layerid, String name, Boolean visible, Boolean animated, String icon,
			BigDecimal tenantid, BigDecimal maxiconzoom, BigDecimal maxlabelzoom, BigDecimal miniconzoom,
			BigDecimal minlabelzoom, Serializable createdate, String creator, String forecolor, Boolean deleted) {
		this.layerid = layerid;
		this.name = name;
		this.visible = visible;
		this.animated = animated;
		this.icon = icon;
		this.tenantid = tenantid;
		this.maxiconzoom = maxiconzoom;
		this.maxlabelzoom = maxlabelzoom;
		this.miniconzoom = miniconzoom;
		this.minlabelzoom = minlabelzoom;
		this.createdate = createdate;
		this.creator = creator;
		this.forecolor = forecolor;
		this.deleted = deleted;
	}

	public BigDecimal getLayerid() {
		return this.layerid;
	}

	public void setLayerid(BigDecimal layerid) {
		this.layerid = layerid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Boolean getVisible() {
		return this.visible;
	}

	public void setVisible(Boolean visible) {
		this.visible = visible;
	}

	public Boolean getAnimated() {
		return this.animated;
	}

	public void setAnimated(Boolean animated) {
		this.animated = animated;
	}

	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	public BigDecimal getTenantid() {
		return this.tenantid;
	}

	public void setTenantid(BigDecimal tenantid) {
		this.tenantid = tenantid;
	}

	public BigDecimal getMaxiconzoom() {
		return this.maxiconzoom;
	}

	public void setMaxiconzoom(BigDecimal maxiconzoom) {
		this.maxiconzoom = maxiconzoom;
	}

	public BigDecimal getMaxlabelzoom() {
		return this.maxlabelzoom;
	}

	public void setMaxlabelzoom(BigDecimal maxlabelzoom) {
		this.maxlabelzoom = maxlabelzoom;
	}

	public BigDecimal getMiniconzoom() {
		return this.miniconzoom;
	}

	public void setMiniconzoom(BigDecimal miniconzoom) {
		this.miniconzoom = miniconzoom;
	}

	public BigDecimal getMinlabelzoom() {
		return this.minlabelzoom;
	}

	public void setMinlabelzoom(BigDecimal minlabelzoom) {
		this.minlabelzoom = minlabelzoom;
	}

	public Serializable getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Serializable createdate) {
		this.createdate = createdate;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public String getForecolor() {
		return this.forecolor;
	}

	public void setForecolor(String forecolor) {
		this.forecolor = forecolor;
	}

	public Boolean getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

}
