package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Mediaitem generated by hbm2java
 */
public class Mediaitem implements java.io.Serializable {

	private BigDecimal mediaitemid;
	private BigDecimal commandid;
	private String commandtype;
	private String plateno;
	private String gpsid;
	private Serializable sendtime;
	private BigDecimal multimediadataid;
	private Integer multimediatype;
	private Integer multidediacodeformat;
	private Integer channelid;
	private Integer eventcode;
	private String filename;
	private Serializable createdate;
	private BigDecimal tenantid;
	private Double latitude;
	private Double longitude;
	private Double speed;

	public Mediaitem() {
	}

	public Mediaitem(BigDecimal mediaitemid) {
		this.mediaitemid = mediaitemid;
	}

	public Mediaitem(BigDecimal mediaitemid, BigDecimal commandid, String commandtype, String plateno, String gpsid,
			Serializable sendtime, BigDecimal multimediadataid, Integer multimediatype, Integer multidediacodeformat,
			Integer channelid, Integer eventcode, String filename, Serializable createdate, BigDecimal tenantid,
			Double latitude, Double longitude, Double speed) {
		this.mediaitemid = mediaitemid;
		this.commandid = commandid;
		this.commandtype = commandtype;
		this.plateno = plateno;
		this.gpsid = gpsid;
		this.sendtime = sendtime;
		this.multimediadataid = multimediadataid;
		this.multimediatype = multimediatype;
		this.multidediacodeformat = multidediacodeformat;
		this.channelid = channelid;
		this.eventcode = eventcode;
		this.filename = filename;
		this.createdate = createdate;
		this.tenantid = tenantid;
		this.latitude = latitude;
		this.longitude = longitude;
		this.speed = speed;
	}

	public BigDecimal getMediaitemid() {
		return this.mediaitemid;
	}

	public void setMediaitemid(BigDecimal mediaitemid) {
		this.mediaitemid = mediaitemid;
	}

	public BigDecimal getCommandid() {
		return this.commandid;
	}

	public void setCommandid(BigDecimal commandid) {
		this.commandid = commandid;
	}

	public String getCommandtype() {
		return this.commandtype;
	}

	public void setCommandtype(String commandtype) {
		this.commandtype = commandtype;
	}

	public String getPlateno() {
		return this.plateno;
	}

	public void setPlateno(String plateno) {
		this.plateno = plateno;
	}

	public String getGpsid() {
		return this.gpsid;
	}

	public void setGpsid(String gpsid) {
		this.gpsid = gpsid;
	}

	public Serializable getSendtime() {
		return this.sendtime;
	}

	public void setSendtime(Serializable sendtime) {
		this.sendtime = sendtime;
	}

	public BigDecimal getMultimediadataid() {
		return this.multimediadataid;
	}

	public void setMultimediadataid(BigDecimal multimediadataid) {
		this.multimediadataid = multimediadataid;
	}

	public Integer getMultimediatype() {
		return this.multimediatype;
	}

	public void setMultimediatype(Integer multimediatype) {
		this.multimediatype = multimediatype;
	}

	public Integer getMultidediacodeformat() {
		return this.multidediacodeformat;
	}

	public void setMultidediacodeformat(Integer multidediacodeformat) {
		this.multidediacodeformat = multidediacodeformat;
	}

	public Integer getChannelid() {
		return this.channelid;
	}

	public void setChannelid(Integer channelid) {
		this.channelid = channelid;
	}

	public Integer getEventcode() {
		return this.eventcode;
	}

	public void setEventcode(Integer eventcode) {
		this.eventcode = eventcode;
	}

	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	public Serializable getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Serializable createdate) {
		this.createdate = createdate;
	}

	public BigDecimal getTenantid() {
		return this.tenantid;
	}

	public void setTenantid(BigDecimal tenantid) {
		this.tenantid = tenantid;
	}

	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	public Double getSpeed() {
		return this.speed;
	}

	public void setSpeed(Double speed) {
		this.speed = speed;
	}

}
