package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Onlineuser generated by hbm2java
 */
public class Onlineuser implements java.io.Serializable {

	private BigDecimal olid;
	private BigDecimal uid;
	private String useraccount;
	private String userid;
	private String username;
	private String userpwd;
	private String appkey;
	private String udid;
	private String os;
	private String osversion;
	private String appvesion;
	private String ver;
	private String usersession;
	private String unique;
	private Serializable logintime;
	private BigDecimal lastonlinetime;
	private String deviceToken;
	private BigDecimal deviceType;
	private String ip;
	private String regionid;
	private String sourceid;
	private BigDecimal usertype;
	private BigDecimal locationtype;
	private BigDecimal locationid;
	private String sort;
	private String sortcolumn;
	private String sortdirection;
	private String role;
	private String cid;

	public Onlineuser() {
	}

	public Onlineuser(BigDecimal olid, BigDecimal uid) {
		this.olid = olid;
		this.uid = uid;
	}

	public Onlineuser(BigDecimal olid, BigDecimal uid, String useraccount, String userid, String username,
			String userpwd, String appkey, String udid, String os, String osversion, String appvesion, String ver,
			String usersession, String unique, Serializable logintime, BigDecimal lastonlinetime, String deviceToken,
			BigDecimal deviceType, String ip, String regionid, String sourceid, BigDecimal usertype,
			BigDecimal locationtype, BigDecimal locationid, String sort, String sortcolumn, String sortdirection,
			String role, String cid) {
		this.olid = olid;
		this.uid = uid;
		this.useraccount = useraccount;
		this.userid = userid;
		this.username = username;
		this.userpwd = userpwd;
		this.appkey = appkey;
		this.udid = udid;
		this.os = os;
		this.osversion = osversion;
		this.appvesion = appvesion;
		this.ver = ver;
		this.usersession = usersession;
		this.unique = unique;
		this.logintime = logintime;
		this.lastonlinetime = lastonlinetime;
		this.deviceToken = deviceToken;
		this.deviceType = deviceType;
		this.ip = ip;
		this.regionid = regionid;
		this.sourceid = sourceid;
		this.usertype = usertype;
		this.locationtype = locationtype;
		this.locationid = locationid;
		this.sort = sort;
		this.sortcolumn = sortcolumn;
		this.sortdirection = sortdirection;
		this.role = role;
		this.cid = cid;
	}

	public BigDecimal getOlid() {
		return this.olid;
	}

	public void setOlid(BigDecimal olid) {
		this.olid = olid;
	}

	public BigDecimal getUid() {
		return this.uid;
	}

	public void setUid(BigDecimal uid) {
		this.uid = uid;
	}

	public String getUseraccount() {
		return this.useraccount;
	}

	public void setUseraccount(String useraccount) {
		this.useraccount = useraccount;
	}

	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getUserpwd() {
		return this.userpwd;
	}

	public void setUserpwd(String userpwd) {
		this.userpwd = userpwd;
	}

	public String getAppkey() {
		return this.appkey;
	}

	public void setAppkey(String appkey) {
		this.appkey = appkey;
	}

	public String getUdid() {
		return this.udid;
	}

	public void setUdid(String udid) {
		this.udid = udid;
	}

	public String getOs() {
		return this.os;
	}

	public void setOs(String os) {
		this.os = os;
	}

	public String getOsversion() {
		return this.osversion;
	}

	public void setOsversion(String osversion) {
		this.osversion = osversion;
	}

	public String getAppvesion() {
		return this.appvesion;
	}

	public void setAppvesion(String appvesion) {
		this.appvesion = appvesion;
	}

	public String getVer() {
		return this.ver;
	}

	public void setVer(String ver) {
		this.ver = ver;
	}

	public String getUsersession() {
		return this.usersession;
	}

	public void setUsersession(String usersession) {
		this.usersession = usersession;
	}

	public String getUnique() {
		return this.unique;
	}

	public void setUnique(String unique) {
		this.unique = unique;
	}

	public Serializable getLogintime() {
		return this.logintime;
	}

	public void setLogintime(Serializable logintime) {
		this.logintime = logintime;
	}

	public BigDecimal getLastonlinetime() {
		return this.lastonlinetime;
	}

	public void setLastonlinetime(BigDecimal lastonlinetime) {
		this.lastonlinetime = lastonlinetime;
	}

	public String getDeviceToken() {
		return this.deviceToken;
	}

	public void setDeviceToken(String deviceToken) {
		this.deviceToken = deviceToken;
	}

	public BigDecimal getDeviceType() {
		return this.deviceType;
	}

	public void setDeviceType(BigDecimal deviceType) {
		this.deviceType = deviceType;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public String getRegionid() {
		return this.regionid;
	}

	public void setRegionid(String regionid) {
		this.regionid = regionid;
	}

	public String getSourceid() {
		return this.sourceid;
	}

	public void setSourceid(String sourceid) {
		this.sourceid = sourceid;
	}

	public BigDecimal getUsertype() {
		return this.usertype;
	}

	public void setUsertype(BigDecimal usertype) {
		this.usertype = usertype;
	}

	public BigDecimal getLocationtype() {
		return this.locationtype;
	}

	public void setLocationtype(BigDecimal locationtype) {
		this.locationtype = locationtype;
	}

	public BigDecimal getLocationid() {
		return this.locationid;
	}

	public void setLocationid(BigDecimal locationid) {
		this.locationid = locationid;
	}

	public String getSort() {
		return this.sort;
	}

	public void setSort(String sort) {
		this.sort = sort;
	}

	public String getSortcolumn() {
		return this.sortcolumn;
	}

	public void setSortcolumn(String sortcolumn) {
		this.sortcolumn = sortcolumn;
	}

	public String getSortdirection() {
		return this.sortdirection;
	}

	public void setSortdirection(String sortdirection) {
		this.sortdirection = sortdirection;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public String getCid() {
		return this.cid;
	}

	public void setCid(String cid) {
		this.cid = cid;
	}

}
