package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Onlinestatic generated by hbm2java
 */
public class Onlinestatic implements java.io.Serializable {

	private BigDecimal id;
	private BigDecimal depid;
	private String depname;
	private BigDecimal onlinenum;
	private BigDecimal vehiclenum;
	private Double onlinerate;
	private Serializable statistictime;
	private BigDecimal interval;

	public Onlinestatic() {
	}

	public Onlinestatic(BigDecimal id) {
		this.id = id;
	}

	public Onlinestatic(BigDecimal id, BigDecimal depid, String depname, BigDecimal onlinenum, BigDecimal vehiclenum,
			Double onlinerate, Serializable statistictime, BigDecimal interval) {
		this.id = id;
		this.depid = depid;
		this.depname = depname;
		this.onlinenum = onlinenum;
		this.vehiclenum = vehiclenum;
		this.onlinerate = onlinerate;
		this.statistictime = statistictime;
		this.interval = interval;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public BigDecimal getDepid() {
		return this.depid;
	}

	public void setDepid(BigDecimal depid) {
		this.depid = depid;
	}

	public String getDepname() {
		return this.depname;
	}

	public void setDepname(String depname) {
		this.depname = depname;
	}

	public BigDecimal getOnlinenum() {
		return this.onlinenum;
	}

	public void setOnlinenum(BigDecimal onlinenum) {
		this.onlinenum = onlinenum;
	}

	public BigDecimal getVehiclenum() {
		return this.vehiclenum;
	}

	public void setVehiclenum(BigDecimal vehiclenum) {
		this.vehiclenum = vehiclenum;
	}

	public Double getOnlinerate() {
		return this.onlinerate;
	}

	public void setOnlinerate(Double onlinerate) {
		this.onlinerate = onlinerate;
	}

	public Serializable getStatistictime() {
		return this.statistictime;
	}

	public void setStatistictime(Serializable statistictime) {
		this.statistictime = statistictime;
	}

	public BigDecimal getInterval() {
		return this.interval;
	}

	public void setInterval(BigDecimal interval) {
		this.interval = interval;
	}

}
