package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Clob;

/**
 * Package generated by hbm2java
 */
public class Package implements java.io.Serializable {

	private BigDecimal id;
	private String name;
	private BigDecimal price;
	private BigDecimal type;
	private BigDecimal flow;
	private BigDecimal state;
	private Serializable createtime;
	private Clob description;

	public Package() {
	}

	public Package(BigDecimal id, String name, BigDecimal price, BigDecimal type, BigDecimal flow, BigDecimal state,
			Serializable createtime) {
		this.id = id;
		this.name = name;
		this.price = price;
		this.type = type;
		this.flow = flow;
		this.state = state;
		this.createtime = createtime;
	}

	public Package(BigDecimal id, String name, BigDecimal price, BigDecimal type, BigDecimal flow, BigDecimal state,
			Serializable createtime, Clob description) {
		this.id = id;
		this.name = name;
		this.price = price;
		this.type = type;
		this.flow = flow;
		this.state = state;
		this.createtime = createtime;
		this.description = description;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public BigDecimal getType() {
		return this.type;
	}

	public void setType(BigDecimal type) {
		this.type = type;
	}

	public BigDecimal getFlow() {
		return this.flow;
	}

	public void setFlow(BigDecimal flow) {
		this.flow = flow;
	}

	public BigDecimal getState() {
		return this.state;
	}

	public void setState(BigDecimal state) {
		this.state = state;
	}

	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	public Clob getDescription() {
		return this.description;
	}

	public void setDescription(Clob description) {
		this.description = description;
	}

}
