package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Packageuser generated by hbm2java
 */
public class Packageuser implements java.io.Serializable {

	private BigDecimal id;
	private String userId;
	private BigDecimal packageId;
	private Serializable buytime;

	public Packageuser() {
	}

	public Packageuser(BigDecimal id) {
		this.id = id;
	}

	public Packageuser(BigDecimal id, String userId, BigDecimal packageId, Serializable buytime) {
		this.id = id;
		this.userId = userId;
		this.packageId = packageId;
		this.buytime = buytime;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public BigDecimal getPackageId() {
		return this.packageId;
	}

	public void setPackageId(BigDecimal packageId) {
		this.packageId = packageId;
	}

	public Serializable getBuytime() {
		return this.buytime;
	}

	public void setBuytime(Serializable buytime) {
		this.buytime = buytime;
	}

}
