package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Paylog generated by hbm2java
 */
public class Paylog implements java.io.Serializable {

	private BigDecimal id;
	private String orderid;
	private String tradeid;
	private double xfsj;
	private double surplusmoney;
	private Serializable tradetime;

	public Paylog() {
	}

	public Paylog(BigDecimal id, String orderid, String tradeid, double xfsj, double surplusmoney,
			Serializable tradetime) {
		this.id = id;
		this.orderid = orderid;
		this.tradeid = tradeid;
		this.xfsj = xfsj;
		this.surplusmoney = surplusmoney;
		this.tradetime = tradetime;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public String getOrderid() {
		return this.orderid;
	}

	public void setOrderid(String orderid) {
		this.orderid = orderid;
	}

	public String getTradeid() {
		return this.tradeid;
	}

	public void setTradeid(String tradeid) {
		this.tradeid = tradeid;
	}

	public double getXfsj() {
		return this.xfsj;
	}

	public void setXfsj(double xfsj) {
		this.xfsj = xfsj;
	}

	public double getSurplusmoney() {
		return this.surplusmoney;
	}

	public void setSurplusmoney(double surplusmoney) {
		this.surplusmoney = surplusmoney;
	}

	public Serializable getTradetime() {
		return this.tradetime;
	}

	public void setTradetime(Serializable tradetime) {
		this.tradetime = tradetime;
	}

}
