package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * Redpackets generated by hbm2java
 */
public class Redpackets implements java.io.Serializable {

	private BigDecimal id;
	private String sender;
	private BigDecimal packettype;
	private String qrcode;
	private BigDecimal price;
	private Date createtime;
	private Date valid;
	private String text;
	private Double longitude;
	private Double latitude;
	private String city;
	private Double radius;
	private BigDecimal number;

	public Redpackets() {
	}

	public Redpackets(BigDecimal id, String sender, BigDecimal packettype, BigDecimal price, Date createtime,
			String text) {
		this.id = id;
		this.sender = sender;
		this.packettype = packettype;
		this.price = price;
		this.createtime = createtime;
		this.text = text;
	}

	public Redpackets(BigDecimal id, String sender, BigDecimal packettype, String qrcode, BigDecimal price,
			Date createtime, Date valid, String text, Double longitude, Double latitude, String city, Double radius,
			BigDecimal number) {
		this.id = id;
		this.sender = sender;
		this.packettype = packettype;
		this.qrcode = qrcode;
		this.price = price;
		this.createtime = createtime;
		this.valid = valid;
		this.text = text;
		this.longitude = longitude;
		this.latitude = latitude;
		this.city = city;
		this.radius = radius;
		this.number = number;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public String getSender() {
		return this.sender;
	}

	public void setSender(String sender) {
		this.sender = sender;
	}

	public BigDecimal getPackettype() {
		return this.packettype;
	}

	public void setPackettype(BigDecimal packettype) {
		this.packettype = packettype;
	}

	public String getQrcode() {
		return this.qrcode;
	}

	public void setQrcode(String qrcode) {
		this.qrcode = qrcode;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public Date getValid() {
		return this.valid;
	}

	public void setValid(Date valid) {
		this.valid = valid;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public Double getRadius() {
		return this.radius;
	}

	public void setRadius(Double radius) {
		this.radius = radius;
	}

	public BigDecimal getNumber() {
		return this.number;
	}

	public void setNumber(BigDecimal number) {
		this.number = number;
	}

}
