package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Redpacketsdtl generated by hbm2java
 */
public class Redpacketsdtl implements java.io.Serializable {

	private BigDecimal id;
	private String holder;
	private String consumershop;
	private Serializable accounttime;
	private Serializable consumptiontime;
	private BigDecimal state;
	private BigDecimal batch;

	public Redpacketsdtl() {
	}

	public Redpacketsdtl(BigDecimal id, BigDecimal state, BigDecimal batch) {
		this.id = id;
		this.state = state;
		this.batch = batch;
	}

	public Redpacketsdtl(BigDecimal id, String holder, String consumershop, Serializable accounttime,
			Serializable consumptiontime, BigDecimal state, BigDecimal batch) {
		this.id = id;
		this.holder = holder;
		this.consumershop = consumershop;
		this.accounttime = accounttime;
		this.consumptiontime = consumptiontime;
		this.state = state;
		this.batch = batch;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public String getHolder() {
		return this.holder;
	}

	public void setHolder(String holder) {
		this.holder = holder;
	}

	public String getConsumershop() {
		return this.consumershop;
	}

	public void setConsumershop(String consumershop) {
		this.consumershop = consumershop;
	}

	public Serializable getAccounttime() {
		return this.accounttime;
	}

	public void setAccounttime(Serializable accounttime) {
		this.accounttime = accounttime;
	}

	public Serializable getConsumptiontime() {
		return this.consumptiontime;
	}

	public void setConsumptiontime(Serializable consumptiontime) {
		this.consumptiontime = consumptiontime;
	}

	public BigDecimal getState() {
		return this.state;
	}

	public void setState(BigDecimal state) {
		this.state = state;
	}

	public BigDecimal getBatch() {
		return this.batch;
	}

	public void setBatch(BigDecimal batch) {
		this.batch = batch;
	}

}
