package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Requestlog generated by hbm2java
 */
public class Requestlog implements java.io.Serializable {

	private BigDecimal id;
	private String imei;
	private BigDecimal rid;
	private String paralist;
	private String url;
	private String ip;
	private Serializable rdate;
	private String methodname;

	public Requestlog() {
	}

	public Requestlog(BigDecimal id, Serializable rdate) {
		this.id = id;
		this.rdate = rdate;
	}

	public Requestlog(BigDecimal id, String imei, BigDecimal rid, String paralist, String url, String ip,
			Serializable rdate, String methodname) {
		this.id = id;
		this.imei = imei;
		this.rid = rid;
		this.paralist = paralist;
		this.url = url;
		this.ip = ip;
		this.rdate = rdate;
		this.methodname = methodname;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public String getImei() {
		return this.imei;
	}

	public void setImei(String imei) {
		this.imei = imei;
	}

	public BigDecimal getRid() {
		return this.rid;
	}

	public void setRid(BigDecimal rid) {
		this.rid = rid;
	}

	public String getParalist() {
		return this.paralist;
	}

	public void setParalist(String paralist) {
		this.paralist = paralist;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public Serializable getRdate() {
		return this.rdate;
	}

	public void setRdate(Serializable rdate) {
		this.rdate = rdate;
	}

	public String getMethodname() {
		return this.methodname;
	}

	public void setMethodname(String methodname) {
		this.methodname = methodname;
	}

}
