package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;

/**
 * RoleDep generated by hbm2java
 */
public class RoleDep implements java.io.Serializable {

	private BigDecimal depid;
	private BigDecimal roleid;

	public RoleDep() {
	}

	public RoleDep(BigDecimal depid, BigDecimal roleid) {
		this.depid = depid;
		this.roleid = roleid;
	}

	public BigDecimal getDepid() {
		return this.depid;
	}

	public void setDepid(BigDecimal depid) {
		this.depid = depid;
	}

	public BigDecimal getRoleid() {
		return this.roleid;
	}

	public void setRoleid(BigDecimal roleid) {
		this.roleid = roleid;
	}

}
