package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {

	private BigDecimal roleid;
	private String name;
	private String code;
	private BigDecimal tenantid;
	private String description;
	private Boolean deleted;

	public Role() {
	}

	public Role(BigDecimal roleid) {
		this.roleid = roleid;
	}

	public Role(BigDecimal roleid, String name, String code, BigDecimal tenantid, String description, Boolean deleted) {
		this.roleid = roleid;
		this.name = name;
		this.code = code;
		this.tenantid = tenantid;
		this.description = description;
		this.deleted = deleted;
	}

	public BigDecimal getRoleid() {
		return this.roleid;
	}

	public void setRoleid(BigDecimal roleid) {
		this.roleid = roleid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public BigDecimal getTenantid() {
		return this.tenantid;
	}

	public void setTenantid(BigDecimal tenantid) {
		this.tenantid = tenantid;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Boolean getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

}
