package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Stoprecord generated by hbm2java
 */
public class Stoprecord implements java.io.Serializable {

	private BigDecimal stopid;
	private String plateno;
	private Serializable starttime;
	private Serializable endtime;
	private Double interval;
	private String location;
	private Double latitude;
	private Double longitude;
	private String status;
	private Double velocity;
	private String driver;
	private BigDecimal processed;
	private String type;
	private Double latitude1;
	private Double longitude1;
	private String location1;
	private String valve;
	private String station;
	private String valvestate;
	private String valvestate1;
	private String videofilename;
	private String doorcheck;
	private String flag;
	private Serializable recordtime;
	private Serializable logtime;
	private Double timespan;
	private String childtype;
	private String remark;
	private Double oil1;
	private Double oil2;
	private Double mileage1;
	private Double mileage2;
	private String imei;

	public Stoprecord() {
	}

	public Stoprecord(BigDecimal stopid) {
		this.stopid = stopid;
	}

	public Stoprecord(BigDecimal stopid, String plateno, Serializable starttime, Serializable endtime, Double interval,
			String location, Double latitude, Double longitude, String status, Double velocity, String driver,
			BigDecimal processed, String type, Double latitude1, Double longitude1, String location1, String valve,
			String station, String valvestate, String valvestate1, String videofilename, String doorcheck, String flag,
			Serializable recordtime, Serializable logtime, Double timespan, String childtype, String remark,
			Double oil1, Double oil2, Double mileage1, Double mileage2, String imei) {
		this.stopid = stopid;
		this.plateno = plateno;
		this.starttime = starttime;
		this.endtime = endtime;
		this.interval = interval;
		this.location = location;
		this.latitude = latitude;
		this.longitude = longitude;
		this.status = status;
		this.velocity = velocity;
		this.driver = driver;
		this.processed = processed;
		this.type = type;
		this.latitude1 = latitude1;
		this.longitude1 = longitude1;
		this.location1 = location1;
		this.valve = valve;
		this.station = station;
		this.valvestate = valvestate;
		this.valvestate1 = valvestate1;
		this.videofilename = videofilename;
		this.doorcheck = doorcheck;
		this.flag = flag;
		this.recordtime = recordtime;
		this.logtime = logtime;
		this.timespan = timespan;
		this.childtype = childtype;
		this.remark = remark;
		this.oil1 = oil1;
		this.oil2 = oil2;
		this.mileage1 = mileage1;
		this.mileage2 = mileage2;
		this.imei = imei;
	}

	public BigDecimal getStopid() {
		return this.stopid;
	}

	public void setStopid(BigDecimal stopid) {
		this.stopid = stopid;
	}

	public String getPlateno() {
		return this.plateno;
	}

	public void setPlateno(String plateno) {
		this.plateno = plateno;
	}

	public Serializable getStarttime() {
		return this.starttime;
	}

	public void setStarttime(Serializable starttime) {
		this.starttime = starttime;
	}

	public Serializable getEndtime() {
		return this.endtime;
	}

	public void setEndtime(Serializable endtime) {
		this.endtime = endtime;
	}

	public Double getInterval() {
		return this.interval;
	}

	public void setInterval(Double interval) {
		this.interval = interval;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Double getVelocity() {
		return this.velocity;
	}

	public void setVelocity(Double velocity) {
		this.velocity = velocity;
	}

	public String getDriver() {
		return this.driver;
	}

	public void setDriver(String driver) {
		this.driver = driver;
	}

	public BigDecimal getProcessed() {
		return this.processed;
	}

	public void setProcessed(BigDecimal processed) {
		this.processed = processed;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Double getLatitude1() {
		return this.latitude1;
	}

	public void setLatitude1(Double latitude1) {
		this.latitude1 = latitude1;
	}

	public Double getLongitude1() {
		return this.longitude1;
	}

	public void setLongitude1(Double longitude1) {
		this.longitude1 = longitude1;
	}

	public String getLocation1() {
		return this.location1;
	}

	public void setLocation1(String location1) {
		this.location1 = location1;
	}

	public String getValve() {
		return this.valve;
	}

	public void setValve(String valve) {
		this.valve = valve;
	}

	public String getStation() {
		return this.station;
	}

	public void setStation(String station) {
		this.station = station;
	}

	public String getValvestate() {
		return this.valvestate;
	}

	public void setValvestate(String valvestate) {
		this.valvestate = valvestate;
	}

	public String getValvestate1() {
		return this.valvestate1;
	}

	public void setValvestate1(String valvestate1) {
		this.valvestate1 = valvestate1;
	}

	public String getVideofilename() {
		return this.videofilename;
	}

	public void setVideofilename(String videofilename) {
		this.videofilename = videofilename;
	}

	public String getDoorcheck() {
		return this.doorcheck;
	}

	public void setDoorcheck(String doorcheck) {
		this.doorcheck = doorcheck;
	}

	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	public Serializable getRecordtime() {
		return this.recordtime;
	}

	public void setRecordtime(Serializable recordtime) {
		this.recordtime = recordtime;
	}

	public Serializable getLogtime() {
		return this.logtime;
	}

	public void setLogtime(Serializable logtime) {
		this.logtime = logtime;
	}

	public Double getTimespan() {
		return this.timespan;
	}

	public void setTimespan(Double timespan) {
		this.timespan = timespan;
	}

	public String getChildtype() {
		return this.childtype;
	}

	public void setChildtype(String childtype) {
		this.childtype = childtype;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Double getOil1() {
		return this.oil1;
	}

	public void setOil1(Double oil1) {
		this.oil1 = oil1;
	}

	public Double getOil2() {
		return this.oil2;
	}

	public void setOil2(Double oil2) {
		this.oil2 = oil2;
	}

	public Double getMileage1() {
		return this.mileage1;
	}

	public void setMileage1(Double mileage1) {
		this.mileage1 = mileage1;
	}

	public Double getMileage2() {
		return this.mileage2;
	}

	public void setMileage2(Double mileage2) {
		this.mileage2 = mileage2;
	}

	public String getImei() {
		return this.imei;
	}

	public void setImei(String imei) {
		this.imei = imei;
	}

}
