package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Blob;

/**
 * SyslogOperate generated by hbm2java
 */
public class SyslogOperate implements java.io.Serializable {

	private BigDecimal operateid;
	private String useraccount;
	private Serializable operatetime;
	private String operateinfo;
	private String operatemenu;
	private Blob remark;
	private BigDecimal operatetype;
	private String plateno;
	private String devicetype;

	public SyslogOperate() {
	}

	public SyslogOperate(BigDecimal operateid, String useraccount, Serializable operatetime) {
		this.operateid = operateid;
		this.useraccount = useraccount;
		this.operatetime = operatetime;
	}

	public SyslogOperate(BigDecimal operateid, String useraccount, Serializable operatetime, String operateinfo,
			String operatemenu, Blob remark, BigDecimal operatetype, String plateno, String devicetype) {
		this.operateid = operateid;
		this.useraccount = useraccount;
		this.operatetime = operatetime;
		this.operateinfo = operateinfo;
		this.operatemenu = operatemenu;
		this.remark = remark;
		this.operatetype = operatetype;
		this.plateno = plateno;
		this.devicetype = devicetype;
	}

	public BigDecimal getOperateid() {
		return this.operateid;
	}

	public void setOperateid(BigDecimal operateid) {
		this.operateid = operateid;
	}

	public String getUseraccount() {
		return this.useraccount;
	}

	public void setUseraccount(String useraccount) {
		this.useraccount = useraccount;
	}

	public Serializable getOperatetime() {
		return this.operatetime;
	}

	public void setOperatetime(Serializable operatetime) {
		this.operatetime = operatetime;
	}

	public String getOperateinfo() {
		return this.operateinfo;
	}

	public void setOperateinfo(String operateinfo) {
		this.operateinfo = operateinfo;
	}

	public String getOperatemenu() {
		return this.operatemenu;
	}

	public void setOperatemenu(String operatemenu) {
		this.operatemenu = operatemenu;
	}

	public Blob getRemark() {
		return this.remark;
	}

	public void setRemark(Blob remark) {
		this.remark = remark;
	}

	public BigDecimal getOperatetype() {
		return this.operatetype;
	}

	public void setOperatetype(BigDecimal operatetype) {
		this.operatetype = operatetype;
	}

	public String getPlateno() {
		return this.plateno;
	}

	public void setPlateno(String plateno) {
		this.plateno = plateno;
	}

	public String getDevicetype() {
		return this.devicetype;
	}

	public void setDevicetype(String devicetype) {
		this.devicetype = devicetype;
	}

}
