package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * TenantUser generated by hbm2java
 */
public class TenantUser implements java.io.Serializable {

	private BigDecimal tenantid;
	private BigDecimal userid;
	private String name;
	private String usertype;
	private String job;
	private BigDecimal department;
	private String phone;
	private String mail;
	private String loginname;
	private String password;
	private Serializable createdate;
	private Boolean admin;
	private Boolean deleted;

	public TenantUser() {
	}

	public TenantUser(BigDecimal tenantid, BigDecimal userid) {
		this.tenantid = tenantid;
		this.userid = userid;
	}

	public TenantUser(BigDecimal tenantid, BigDecimal userid, String name, String usertype, String job,
			BigDecimal department, String phone, String mail, String loginname, String password,
			Serializable createdate, Boolean admin, Boolean deleted) {
		this.tenantid = tenantid;
		this.userid = userid;
		this.name = name;
		this.usertype = usertype;
		this.job = job;
		this.department = department;
		this.phone = phone;
		this.mail = mail;
		this.loginname = loginname;
		this.password = password;
		this.createdate = createdate;
		this.admin = admin;
		this.deleted = deleted;
	}

	public BigDecimal getTenantid() {
		return this.tenantid;
	}

	public void setTenantid(BigDecimal tenantid) {
		this.tenantid = tenantid;
	}

	public BigDecimal getUserid() {
		return this.userid;
	}

	public void setUserid(BigDecimal userid) {
		this.userid = userid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getUsertype() {
		return this.usertype;
	}

	public void setUsertype(String usertype) {
		this.usertype = usertype;
	}

	public String getJob() {
		return this.job;
	}

	public void setJob(String job) {
		this.job = job;
	}

	public BigDecimal getDepartment() {
		return this.department;
	}

	public void setDepartment(BigDecimal department) {
		this.department = department;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	public String getLoginname() {
		return this.loginname;
	}

	public void setLoginname(String loginname) {
		this.loginname = loginname;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Serializable getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Serializable createdate) {
		this.createdate = createdate;
	}

	public Boolean getAdmin() {
		return this.admin;
	}

	public void setAdmin(Boolean admin) {
		this.admin = admin;
	}

	public Boolean getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

}
