package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Terminalparam generated by hbm2java
 */
public class Terminalparam implements java.io.Serializable {

	private BigDecimal paramid;
	private String gpsid;
	private String plateno;
	private String code;
	private String value;
	private String fieldtype;
	private Serializable createdate;
	private Serializable updatedate;
	private String status;
	private BigDecimal sn;

	public Terminalparam() {
	}

	public Terminalparam(BigDecimal paramid) {
		this.paramid = paramid;
	}

	public Terminalparam(BigDecimal paramid, String gpsid, String plateno, String code, String value, String fieldtype,
			Serializable createdate, Serializable updatedate, String status, BigDecimal sn) {
		this.paramid = paramid;
		this.gpsid = gpsid;
		this.plateno = plateno;
		this.code = code;
		this.value = value;
		this.fieldtype = fieldtype;
		this.createdate = createdate;
		this.updatedate = updatedate;
		this.status = status;
		this.sn = sn;
	}

	public BigDecimal getParamid() {
		return this.paramid;
	}

	public void setParamid(BigDecimal paramid) {
		this.paramid = paramid;
	}

	public String getGpsid() {
		return this.gpsid;
	}

	public void setGpsid(String gpsid) {
		this.gpsid = gpsid;
	}

	public String getPlateno() {
		return this.plateno;
	}

	public void setPlateno(String plateno) {
		this.plateno = plateno;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public String getFieldtype() {
		return this.fieldtype;
	}

	public void setFieldtype(String fieldtype) {
		this.fieldtype = fieldtype;
	}

	public Serializable getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Serializable createdate) {
		this.createdate = createdate;
	}

	public Serializable getUpdatedate() {
		return this.updatedate;
	}

	public void setUpdatedate(Serializable updatedate) {
		this.updatedate = updatedate;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public BigDecimal getSn() {
		return this.sn;
	}

	public void setSn(BigDecimal sn) {
		this.sn = sn;
	}

}
