package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Terminalcommand generated by hbm2java
 */
public class Terminalcommand implements java.io.Serializable {

	private BigDecimal cmdid;
	private String gpsid;
	private String plateno;
	private BigDecimal cmdtype;
	private String cmd;
	private String data;
	private Serializable createdate;
	private String owner;
	private String status;
	private String remark;
	private BigDecimal sn;
	private BigDecimal userid;
	private String imei;
	private String devicemodel;

	public Terminalcommand() {
	}

	public Terminalcommand(BigDecimal cmdid) {
		this.cmdid = cmdid;
	}

	public Terminalcommand(BigDecimal cmdid, String gpsid, String plateno, BigDecimal cmdtype, String cmd, String data,
			Serializable createdate, String owner, String status, String remark, BigDecimal sn, BigDecimal userid,
			String imei, String devicemodel) {
		this.cmdid = cmdid;
		this.gpsid = gpsid;
		this.plateno = plateno;
		this.cmdtype = cmdtype;
		this.cmd = cmd;
		this.data = data;
		this.createdate = createdate;
		this.owner = owner;
		this.status = status;
		this.remark = remark;
		this.sn = sn;
		this.userid = userid;
		this.imei = imei;
		this.devicemodel = devicemodel;
	}

	public BigDecimal getCmdid() {
		return this.cmdid;
	}

	public void setCmdid(BigDecimal cmdid) {
		this.cmdid = cmdid;
	}

	public String getGpsid() {
		return this.gpsid;
	}

	public void setGpsid(String gpsid) {
		this.gpsid = gpsid;
	}

	public String getPlateno() {
		return this.plateno;
	}

	public void setPlateno(String plateno) {
		this.plateno = plateno;
	}

	public BigDecimal getCmdtype() {
		return this.cmdtype;
	}

	public void setCmdtype(BigDecimal cmdtype) {
		this.cmdtype = cmdtype;
	}

	public String getCmd() {
		return this.cmd;
	}

	public void setCmd(String cmd) {
		this.cmd = cmd;
	}

	public String getData() {
		return this.data;
	}

	public void setData(String data) {
		this.data = data;
	}

	public Serializable getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Serializable createdate) {
		this.createdate = createdate;
	}

	public String getOwner() {
		return this.owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public BigDecimal getSn() {
		return this.sn;
	}

	public void setSn(BigDecimal sn) {
		this.sn = sn;
	}

	public BigDecimal getUserid() {
		return this.userid;
	}

	public void setUserid(BigDecimal userid) {
		this.userid = userid;
	}

	public String getImei() {
		return this.imei;
	}

	public void setImei(String imei) {
		this.imei = imei;
	}

	public String getDevicemodel() {
		return this.devicemodel;
	}

	public void setDevicemodel(String devicemodel) {
		this.devicemodel = devicemodel;
	}

}
