package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;

/**
 * Test generated by hbm2java
 */
public class Test implements java.io.Serializable {

	private BigDecimal id;
	private String name;

	public Test() {
	}

	public Test(BigDecimal id) {
		this.id = id;
	}

	public Test(BigDecimal id, String name) {
		this.id = id;
		this.name = name;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
