package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;

/**
 * UserRole generated by hbm2java
 */
public class UserRole implements java.io.Serializable {

	private BigDecimal userid;
	private BigDecimal roleid;

	public UserRole() {
	}

	public UserRole(BigDecimal userid, BigDecimal roleid) {
		this.userid = userid;
		this.roleid = roleid;
	}

	public BigDecimal getUserid() {
		return this.userid;
	}

	public void setUserid(BigDecimal userid) {
		this.userid = userid;
	}

	public BigDecimal getRoleid() {
		return this.roleid;
	}

	public void setRoleid(BigDecimal roleid) {
		this.roleid = roleid;
	}

}
