package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Vehiclerecorder generated by hbm2java
 */
public class Vehiclerecorder implements java.io.Serializable {

	private BigDecimal recorderid;
	private BigDecimal command;
	private String recorderdata;
	private String plateno;
	private Integer platecolor;
	private Serializable createdate;
	private Serializable recorderdate;
	private BigDecimal tenantid;

	public Vehiclerecorder() {
	}

	public Vehiclerecorder(BigDecimal recorderid) {
		this.recorderid = recorderid;
	}

	public Vehiclerecorder(BigDecimal recorderid, BigDecimal command, String recorderdata, String plateno,
			Integer platecolor, Serializable createdate, Serializable recorderdate, BigDecimal tenantid) {
		this.recorderid = recorderid;
		this.command = command;
		this.recorderdata = recorderdata;
		this.plateno = plateno;
		this.platecolor = platecolor;
		this.createdate = createdate;
		this.recorderdate = recorderdate;
		this.tenantid = tenantid;
	}

	public BigDecimal getRecorderid() {
		return this.recorderid;
	}

	public void setRecorderid(BigDecimal recorderid) {
		this.recorderid = recorderid;
	}

	public BigDecimal getCommand() {
		return this.command;
	}

	public void setCommand(BigDecimal command) {
		this.command = command;
	}

	public String getRecorderdata() {
		return this.recorderdata;
	}

	public void setRecorderdata(String recorderdata) {
		this.recorderdata = recorderdata;
	}

	public String getPlateno() {
		return this.plateno;
	}

	public void setPlateno(String plateno) {
		this.plateno = plateno;
	}

	public Integer getPlatecolor() {
		return this.platecolor;
	}

	public void setPlatecolor(Integer platecolor) {
		this.platecolor = platecolor;
	}

	public Serializable getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Serializable createdate) {
		this.createdate = createdate;
	}

	public Serializable getRecorderdate() {
		return this.recorderdate;
	}

	public void setRecorderdate(Serializable recorderdate) {
		this.recorderdate = recorderdate;
	}

	public BigDecimal getTenantid() {
		return this.tenantid;
	}

	public void setTenantid(BigDecimal tenantid) {
		this.tenantid = tenantid;
	}

}
