package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;

/**
 * Vehicletype generated by hbm2java
 */
public class Vehicletype implements java.io.Serializable {

	private BigDecimal vtid;
	private String vtname;
	private String vticon;

	public Vehicletype() {
	}

	public Vehicletype(BigDecimal vtid, String vtname) {
		this.vtid = vtid;
		this.vtname = vtname;
	}

	public Vehicletype(BigDecimal vtid, String vtname, String vticon) {
		this.vtid = vtid;
		this.vtname = vtname;
		this.vticon = vticon;
	}

	public BigDecimal getVtid() {
		return this.vtid;
	}

	public void setVtid(BigDecimal vtid) {
		this.vtid = vtid;
	}

	public String getVtname() {
		return this.vtname;
	}

	public void setVtname(String vtname) {
		this.vtname = vtname;
	}

	public String getVticon() {
		return this.vticon;
	}

	public void setVticon(String vticon) {
		this.vticon = vticon;
	}

}
