package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;

/**
 * Vehiclemodel generated by hbm2java
 */
public class Vehiclemodel implements java.io.Serializable {

	private BigDecimal vbid;
	private BigDecimal vtid;
	private String vbname;

	public Vehiclemodel() {
	}

	public Vehiclemodel(BigDecimal vbid, BigDecimal vtid, String vbname) {
		this.vbid = vbid;
		this.vtid = vtid;
		this.vbname = vbname;
	}

	public BigDecimal getVbid() {
		return this.vbid;
	}

	public void setVbid(BigDecimal vbid) {
		this.vbid = vbid;
	}

	public BigDecimal getVtid() {
		return this.vtid;
	}

	public void setVtid(BigDecimal vtid) {
		this.vtid = vtid;
	}

	public String getVbname() {
		return this.vbname;
	}

	public void setVbname(String vbname) {
		this.vbname = vbname;
	}

}
