package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Vehicle generated by hbm2java
 */
public class Vehicle implements java.io.Serializable {

	private BigDecimal vehicleid;
	private String plateno;
	private String type;
	private String unit;
	private String monitor;
	private Double weight;
	private String driver;
	private String status;
	private Boolean measure;
	private Double total;
	private Double remain;
	private Boolean deleted;
	private Serializable createdate;
	private BigDecimal tenantid;
	private String gpsida;
	private String truck;
	private String gpsidb;
	private Double initremain;
	private String videodeviceid;
	private BigDecimal sortid;
	private String vehicledevicetype;
	private BigDecimal dvronline;
	private Boolean authorize;
	private String motorid;
	private Serializable intalldate;
	private String gpscard;
	private String dvrcard;
	private String drivermobile;
	private String monitormobile;
	private String loginname;
	private String password;
	private String can;
	private String cabnum;
	private String childno;
	private Serializable lastchecktime;
	private String listenip;
	private String listenport;
	private Serializable onlinetime;
	private Serializable offlinetime;
	private Serializable updatelogdate;
	private Double flowrate;
	private String diskstate;
	private Serializable logtime;
	private String industry;
	private String runstatus;
	private String gpsid;
	private BigDecimal depid;
	private BigDecimal color;
	private String gpsterminaltype;
	private Serializable installdate;
	private String simno;
	private String routes;
	private String imei;
	private String mobile;
	private BigDecimal comid;
	private String jtjid;
	private BigDecimal istranster;
	private Serializable expiredate;
	private BigDecimal carindustry;
	private String vehicleidnumber;
	private BigDecimal isdel;
	private BigDecimal islock;
	private Double oil;
	private BigDecimal vmoney;
	private BigDecimal vmonth;
	private Serializable vbdate;
	private Serializable vedate;
	private BigDecimal isopenvoice;
	private BigDecimal isobd;
	private Serializable obdinstalldate;
	private String obdtype;
	private String obdbrand;
	private Double totaltrack;
	private Double addtrack;
	private BigDecimal isdefense;

	public Vehicle() {
	}

	public Vehicle(BigDecimal vehicleid) {
		this.vehicleid = vehicleid;
	}

	public Vehicle(BigDecimal vehicleid, String plateno, String type, String unit, String monitor, Double weight,
			String driver, String status, Boolean measure, Double total, Double remain, Boolean deleted,
			Serializable createdate, BigDecimal tenantid, String gpsida, String truck, String gpsidb, Double initremain,
			String videodeviceid, BigDecimal sortid, String vehicledevicetype, BigDecimal dvronline, Boolean authorize,
			String motorid, Serializable intalldate, String gpscard, String dvrcard, String drivermobile,
			String monitormobile, String loginname, String password, String can, String cabnum, String childno,
			Serializable lastchecktime, String listenip, String listenport, Serializable onlinetime,
			Serializable offlinetime, Serializable updatelogdate, Double flowrate, String diskstate,
			Serializable logtime, String industry, String runstatus, String gpsid, BigDecimal depid, BigDecimal color,
			String gpsterminaltype, Serializable installdate, String simno, String routes, String imei, String mobile,
			BigDecimal comid, String jtjid, BigDecimal istranster, Serializable expiredate, BigDecimal carindustry,
			String vehicleidnumber, BigDecimal isdel, BigDecimal islock, Double oil, BigDecimal vmoney,
			BigDecimal vmonth, Serializable vbdate, Serializable vedate, BigDecimal isopenvoice, BigDecimal isobd,
			Serializable obdinstalldate, String obdtype, String obdbrand, Double totaltrack, Double addtrack,
			BigDecimal isdefense) {
		this.vehicleid = vehicleid;
		this.plateno = plateno;
		this.type = type;
		this.unit = unit;
		this.monitor = monitor;
		this.weight = weight;
		this.driver = driver;
		this.status = status;
		this.measure = measure;
		this.total = total;
		this.remain = remain;
		this.deleted = deleted;
		this.createdate = createdate;
		this.tenantid = tenantid;
		this.gpsida = gpsida;
		this.truck = truck;
		this.gpsidb = gpsidb;
		this.initremain = initremain;
		this.videodeviceid = videodeviceid;
		this.sortid = sortid;
		this.vehicledevicetype = vehicledevicetype;
		this.dvronline = dvronline;
		this.authorize = authorize;
		this.motorid = motorid;
		this.intalldate = intalldate;
		this.gpscard = gpscard;
		this.dvrcard = dvrcard;
		this.drivermobile = drivermobile;
		this.monitormobile = monitormobile;
		this.loginname = loginname;
		this.password = password;
		this.can = can;
		this.cabnum = cabnum;
		this.childno = childno;
		this.lastchecktime = lastchecktime;
		this.listenip = listenip;
		this.listenport = listenport;
		this.onlinetime = onlinetime;
		this.offlinetime = offlinetime;
		this.updatelogdate = updatelogdate;
		this.flowrate = flowrate;
		this.diskstate = diskstate;
		this.logtime = logtime;
		this.industry = industry;
		this.runstatus = runstatus;
		this.gpsid = gpsid;
		this.depid = depid;
		this.color = color;
		this.gpsterminaltype = gpsterminaltype;
		this.installdate = installdate;
		this.simno = simno;
		this.routes = routes;
		this.imei = imei;
		this.mobile = mobile;
		this.comid = comid;
		this.jtjid = jtjid;
		this.istranster = istranster;
		this.expiredate = expiredate;
		this.carindustry = carindustry;
		this.vehicleidnumber = vehicleidnumber;
		this.isdel = isdel;
		this.islock = islock;
		this.oil = oil;
		this.vmoney = vmoney;
		this.vmonth = vmonth;
		this.vbdate = vbdate;
		this.vedate = vedate;
		this.isopenvoice = isopenvoice;
		this.isobd = isobd;
		this.obdinstalldate = obdinstalldate;
		this.obdtype = obdtype;
		this.obdbrand = obdbrand;
		this.totaltrack = totaltrack;
		this.addtrack = addtrack;
		this.isdefense = isdefense;
	}

	public BigDecimal getVehicleid() {
		return this.vehicleid;
	}

	public void setVehicleid(BigDecimal vehicleid) {
		this.vehicleid = vehicleid;
	}

	public String getPlateno() {
		return this.plateno;
	}

	public void setPlateno(String plateno) {
		this.plateno = plateno;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	public String getMonitor() {
		return this.monitor;
	}

	public void setMonitor(String monitor) {
		this.monitor = monitor;
	}

	public Double getWeight() {
		return this.weight;
	}

	public void setWeight(Double weight) {
		this.weight = weight;
	}

	public String getDriver() {
		return this.driver;
	}

	public void setDriver(String driver) {
		this.driver = driver;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Boolean getMeasure() {
		return this.measure;
	}

	public void setMeasure(Boolean measure) {
		this.measure = measure;
	}

	public Double getTotal() {
		return this.total;
	}

	public void setTotal(Double total) {
		this.total = total;
	}

	public Double getRemain() {
		return this.remain;
	}

	public void setRemain(Double remain) {
		this.remain = remain;
	}

	public Boolean getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

	public Serializable getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Serializable createdate) {
		this.createdate = createdate;
	}

	public BigDecimal getTenantid() {
		return this.tenantid;
	}

	public void setTenantid(BigDecimal tenantid) {
		this.tenantid = tenantid;
	}

	public String getGpsida() {
		return this.gpsida;
	}

	public void setGpsida(String gpsida) {
		this.gpsida = gpsida;
	}

	public String getTruck() {
		return this.truck;
	}

	public void setTruck(String truck) {
		this.truck = truck;
	}

	public String getGpsidb() {
		return this.gpsidb;
	}

	public void setGpsidb(String gpsidb) {
		this.gpsidb = gpsidb;
	}

	public Double getInitremain() {
		return this.initremain;
	}

	public void setInitremain(Double initremain) {
		this.initremain = initremain;
	}

	public String getVideodeviceid() {
		return this.videodeviceid;
	}

	public void setVideodeviceid(String videodeviceid) {
		this.videodeviceid = videodeviceid;
	}

	public BigDecimal getSortid() {
		return this.sortid;
	}

	public void setSortid(BigDecimal sortid) {
		this.sortid = sortid;
	}

	public String getVehicledevicetype() {
		return this.vehicledevicetype;
	}

	public void setVehicledevicetype(String vehicledevicetype) {
		this.vehicledevicetype = vehicledevicetype;
	}

	public BigDecimal getDvronline() {
		return this.dvronline;
	}

	public void setDvronline(BigDecimal dvronline) {
		this.dvronline = dvronline;
	}

	public Boolean getAuthorize() {
		return this.authorize;
	}

	public void setAuthorize(Boolean authorize) {
		this.authorize = authorize;
	}

	public String getMotorid() {
		return this.motorid;
	}

	public void setMotorid(String motorid) {
		this.motorid = motorid;
	}

	public Serializable getIntalldate() {
		return this.intalldate;
	}

	public void setIntalldate(Serializable intalldate) {
		this.intalldate = intalldate;
	}

	public String getGpscard() {
		return this.gpscard;
	}

	public void setGpscard(String gpscard) {
		this.gpscard = gpscard;
	}

	public String getDvrcard() {
		return this.dvrcard;
	}

	public void setDvrcard(String dvrcard) {
		this.dvrcard = dvrcard;
	}

	public String getDrivermobile() {
		return this.drivermobile;
	}

	public void setDrivermobile(String drivermobile) {
		this.drivermobile = drivermobile;
	}

	public String getMonitormobile() {
		return this.monitormobile;
	}

	public void setMonitormobile(String monitormobile) {
		this.monitormobile = monitormobile;
	}

	public String getLoginname() {
		return this.loginname;
	}

	public void setLoginname(String loginname) {
		this.loginname = loginname;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getCan() {
		return this.can;
	}

	public void setCan(String can) {
		this.can = can;
	}

	public String getCabnum() {
		return this.cabnum;
	}

	public void setCabnum(String cabnum) {
		this.cabnum = cabnum;
	}

	public String getChildno() {
		return this.childno;
	}

	public void setChildno(String childno) {
		this.childno = childno;
	}

	public Serializable getLastchecktime() {
		return this.lastchecktime;
	}

	public void setLastchecktime(Serializable lastchecktime) {
		this.lastchecktime = lastchecktime;
	}

	public String getListenip() {
		return this.listenip;
	}

	public void setListenip(String listenip) {
		this.listenip = listenip;
	}

	public String getListenport() {
		return this.listenport;
	}

	public void setListenport(String listenport) {
		this.listenport = listenport;
	}

	public Serializable getOnlinetime() {
		return this.onlinetime;
	}

	public void setOnlinetime(Serializable onlinetime) {
		this.onlinetime = onlinetime;
	}

	public Serializable getOfflinetime() {
		return this.offlinetime;
	}

	public void setOfflinetime(Serializable offlinetime) {
		this.offlinetime = offlinetime;
	}

	public Serializable getUpdatelogdate() {
		return this.updatelogdate;
	}

	public void setUpdatelogdate(Serializable updatelogdate) {
		this.updatelogdate = updatelogdate;
	}

	public Double getFlowrate() {
		return this.flowrate;
	}

	public void setFlowrate(Double flowrate) {
		this.flowrate = flowrate;
	}

	public String getDiskstate() {
		return this.diskstate;
	}

	public void setDiskstate(String diskstate) {
		this.diskstate = diskstate;
	}

	public Serializable getLogtime() {
		return this.logtime;
	}

	public void setLogtime(Serializable logtime) {
		this.logtime = logtime;
	}

	public String getIndustry() {
		return this.industry;
	}

	public void setIndustry(String industry) {
		this.industry = industry;
	}

	public String getRunstatus() {
		return this.runstatus;
	}

	public void setRunstatus(String runstatus) {
		this.runstatus = runstatus;
	}

	public String getGpsid() {
		return this.gpsid;
	}

	public void setGpsid(String gpsid) {
		this.gpsid = gpsid;
	}

	public BigDecimal getDepid() {
		return this.depid;
	}

	public void setDepid(BigDecimal depid) {
		this.depid = depid;
	}

	public BigDecimal getColor() {
		return this.color;
	}

	public void setColor(BigDecimal color) {
		this.color = color;
	}

	public String getGpsterminaltype() {
		return this.gpsterminaltype;
	}

	public void setGpsterminaltype(String gpsterminaltype) {
		this.gpsterminaltype = gpsterminaltype;
	}

	public Serializable getInstalldate() {
		return this.installdate;
	}

	public void setInstalldate(Serializable installdate) {
		this.installdate = installdate;
	}

	public String getSimno() {
		return this.simno;
	}

	public void setSimno(String simno) {
		this.simno = simno;
	}

	public String getRoutes() {
		return this.routes;
	}

	public void setRoutes(String routes) {
		this.routes = routes;
	}

	public String getImei() {
		return this.imei;
	}

	public void setImei(String imei) {
		this.imei = imei;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public BigDecimal getComid() {
		return this.comid;
	}

	public void setComid(BigDecimal comid) {
		this.comid = comid;
	}

	public String getJtjid() {
		return this.jtjid;
	}

	public void setJtjid(String jtjid) {
		this.jtjid = jtjid;
	}

	public BigDecimal getIstranster() {
		return this.istranster;
	}

	public void setIstranster(BigDecimal istranster) {
		this.istranster = istranster;
	}

	public Serializable getExpiredate() {
		return this.expiredate;
	}

	public void setExpiredate(Serializable expiredate) {
		this.expiredate = expiredate;
	}

	public BigDecimal getCarindustry() {
		return this.carindustry;
	}

	public void setCarindustry(BigDecimal carindustry) {
		this.carindustry = carindustry;
	}

	public String getVehicleidnumber() {
		return this.vehicleidnumber;
	}

	public void setVehicleidnumber(String vehicleidnumber) {
		this.vehicleidnumber = vehicleidnumber;
	}

	public BigDecimal getIsdel() {
		return this.isdel;
	}

	public void setIsdel(BigDecimal isdel) {
		this.isdel = isdel;
	}

	public BigDecimal getIslock() {
		return this.islock;
	}

	public void setIslock(BigDecimal islock) {
		this.islock = islock;
	}

	public Double getOil() {
		return this.oil;
	}

	public void setOil(Double oil) {
		this.oil = oil;
	}

	public BigDecimal getVmoney() {
		return this.vmoney;
	}

	public void setVmoney(BigDecimal vmoney) {
		this.vmoney = vmoney;
	}

	public BigDecimal getVmonth() {
		return this.vmonth;
	}

	public void setVmonth(BigDecimal vmonth) {
		this.vmonth = vmonth;
	}

	public Serializable getVbdate() {
		return this.vbdate;
	}

	public void setVbdate(Serializable vbdate) {
		this.vbdate = vbdate;
	}

	public Serializable getVedate() {
		return this.vedate;
	}

	public void setVedate(Serializable vedate) {
		this.vedate = vedate;
	}

	public BigDecimal getIsopenvoice() {
		return this.isopenvoice;
	}

	public void setIsopenvoice(BigDecimal isopenvoice) {
		this.isopenvoice = isopenvoice;
	}

	public BigDecimal getIsobd() {
		return this.isobd;
	}

	public void setIsobd(BigDecimal isobd) {
		this.isobd = isobd;
	}

	public Serializable getObdinstalldate() {
		return this.obdinstalldate;
	}

	public void setObdinstalldate(Serializable obdinstalldate) {
		this.obdinstalldate = obdinstalldate;
	}

	public String getObdtype() {
		return this.obdtype;
	}

	public void setObdtype(String obdtype) {
		this.obdtype = obdtype;
	}

	public String getObdbrand() {
		return this.obdbrand;
	}

	public void setObdbrand(String obdbrand) {
		this.obdbrand = obdbrand;
	}

	public Double getTotaltrack() {
		return this.totaltrack;
	}

	public void setTotaltrack(Double totaltrack) {
		this.totaltrack = totaltrack;
	}

	public Double getAddtrack() {
		return this.addtrack;
	}

	public void setAddtrack(Double addtrack) {
		this.addtrack = addtrack;
	}

	public BigDecimal getIsdefense() {
		return this.isdefense;
	}

	public void setIsdefense(BigDecimal isdefense) {
		this.isdefense = isdefense;
	}

}
