package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.sql.Clob;
import java.util.Date;

/**
 * Violationrecord generated by hbm2java
 */
public class Violationrecord implements java.io.Serializable {

	private BigDecimal id;
	private Date updatetime;
	private Clob rectext;
	private String imei;

	public Violationrecord() {
	}

	public Violationrecord(BigDecimal id, Date updatetime, String imei) {
		this.id = id;
		this.updatetime = updatetime;
		this.imei = imei;
	}

	public Violationrecord(BigDecimal id, Date updatetime, Clob rectext, String imei) {
		this.id = id;
		this.updatetime = updatetime;
		this.rectext = rectext;
		this.imei = imei;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	public Clob getRectext() {
		return this.rectext;
	}

	public void setRectext(Clob rectext) {
		this.rectext = rectext;
	}

	public String getImei() {
		return this.imei;
	}

	public void setImei(String imei) {
		this.imei = imei;
	}

}
