package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;

/**
 * WeatherCity generated by hbm2java
 */
public class WeatherCity implements java.io.Serializable {

	private BigDecimal id;
	private String name;
	private BigDecimal pid;
	private String cid;
	private String cityCode;
	private BigDecimal engine;
	private BigDecimal engineno;
	private BigDecimal carclass;
	private BigDecimal classa;
	private BigDecimal classno;
	private BigDecimal regist;
	private BigDecimal registno;
	private String addr;
	private String carabbr;

	public WeatherCity() {
	}

	public WeatherCity(BigDecimal id) {
		this.id = id;
	}

	public WeatherCity(BigDecimal id, String name, BigDecimal pid, String cid, String cityCode, BigDecimal engine,
			BigDecimal engineno, BigDecimal carclass, BigDecimal classa, BigDecimal classno, BigDecimal regist,
			BigDecimal registno, String addr, String carabbr) {
		this.id = id;
		this.name = name;
		this.pid = pid;
		this.cid = cid;
		this.cityCode = cityCode;
		this.engine = engine;
		this.engineno = engineno;
		this.carclass = carclass;
		this.classa = classa;
		this.classno = classno;
		this.regist = regist;
		this.registno = registno;
		this.addr = addr;
		this.carabbr = carabbr;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public BigDecimal getPid() {
		return this.pid;
	}

	public void setPid(BigDecimal pid) {
		this.pid = pid;
	}

	public String getCid() {
		return this.cid;
	}

	public void setCid(String cid) {
		this.cid = cid;
	}

	public String getCityCode() {
		return this.cityCode;
	}

	public void setCityCode(String cityCode) {
		this.cityCode = cityCode;
	}

	public BigDecimal getEngine() {
		return this.engine;
	}

	public void setEngine(BigDecimal engine) {
		this.engine = engine;
	}

	public BigDecimal getEngineno() {
		return this.engineno;
	}

	public void setEngineno(BigDecimal engineno) {
		this.engineno = engineno;
	}

	public BigDecimal getCarclass() {
		return this.carclass;
	}

	public void setCarclass(BigDecimal carclass) {
		this.carclass = carclass;
	}

	public BigDecimal getClassa() {
		return this.classa;
	}

	public void setClassa(BigDecimal classa) {
		this.classa = classa;
	}

	public BigDecimal getClassno() {
		return this.classno;
	}

	public void setClassno(BigDecimal classno) {
		this.classno = classno;
	}

	public BigDecimal getRegist() {
		return this.regist;
	}

	public void setRegist(BigDecimal regist) {
		this.regist = regist;
	}

	public BigDecimal getRegistno() {
		return this.registno;
	}

	public void setRegistno(BigDecimal registno) {
		this.registno = registno;
	}

	public String getAddr() {
		return this.addr;
	}

	public void setAddr(String addr) {
		this.addr = addr;
	}

	public String getCarabbr() {
		return this.carabbr;
	}

	public void setCarabbr(String carabbr) {
		this.carabbr = carabbr;
	}

}
