package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;

/**
 * WeatherDistrict generated by hbm2java
 */
public class WeatherDistrict implements java.io.Serializable {

	private BigDecimal id;
	private String name;
	private BigDecimal pid;
	private String cid;
	private String did;
	private BigDecimal code;

	public WeatherDistrict() {
	}

	public WeatherDistrict(BigDecimal id) {
		this.id = id;
	}

	public WeatherDistrict(BigDecimal id, String name, BigDecimal pid, String cid, String did, BigDecimal code) {
		this.id = id;
		this.name = name;
		this.pid = pid;
		this.cid = cid;
		this.did = did;
		this.code = code;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public BigDecimal getPid() {
		return this.pid;
	}

	public void setPid(BigDecimal pid) {
		this.pid = pid;
	}

	public String getCid() {
		return this.cid;
	}

	public void setCid(String cid) {
		this.cid = cid;
	}

	public String getDid() {
		return this.did;
	}

	public void setDid(String did) {
		this.did = did;
	}

	public BigDecimal getCode() {
		return this.code;
	}

	public void setCode(BigDecimal code) {
		this.code = code;
	}

}
