package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;

/**
 * WeatherProvince generated by hbm2java
 */
public class WeatherProvince implements java.io.Serializable {

	private BigDecimal id;
	private String name;
	private BigDecimal pid;

	public WeatherProvince() {
	}

	public WeatherProvince(BigDecimal id, BigDecimal pid) {
		this.id = id;
		this.pid = pid;
	}

	public WeatherProvince(BigDecimal id, String name, BigDecimal pid) {
		this.id = id;
		this.name = name;
		this.pid = pid;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public BigDecimal getPid() {
		return this.pid;
	}

	public void setPid(BigDecimal pid) {
		this.pid = pid;
	}

}
