package com.lmkj.pojo;
// Generated 2016-9-28 9:15:49 by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Wechatorder generated by hbm2java
 */
public class Wechatorder implements java.io.Serializable {

	private BigDecimal id;
	private Date orderdate;
	private String orderid;
	private String xfdemo;
	private BigDecimal orderstatus;
	private BigDecimal cid;
	private String imei;
	private BigDecimal ye;
	private BigDecimal price;
	private String userid;
	private BigDecimal czje;
	private Serializable confiredate;
	private BigDecimal takeeffect;
	private String description;
	private String alipaytradeno;
	private BigDecimal paytype;

	public Wechatorder() {
	}

	public Wechatorder(BigDecimal id, Date orderdate, String orderid, String imei) {
		this.id = id;
		this.orderdate = orderdate;
		this.orderid = orderid;
		this.imei = imei;
	}

	public Wechatorder(BigDecimal id, Date orderdate, String orderid, String xfdemo, BigDecimal orderstatus,
			BigDecimal cid, String imei, BigDecimal ye, BigDecimal price, String userid, BigDecimal czje,
			Serializable confiredate, BigDecimal takeeffect, String description, String alipaytradeno,
			BigDecimal paytype) {
		this.id = id;
		this.orderdate = orderdate;
		this.orderid = orderid;
		this.xfdemo = xfdemo;
		this.orderstatus = orderstatus;
		this.cid = cid;
		this.imei = imei;
		this.ye = ye;
		this.price = price;
		this.userid = userid;
		this.czje = czje;
		this.confiredate = confiredate;
		this.takeeffect = takeeffect;
		this.description = description;
		this.alipaytradeno = alipaytradeno;
		this.paytype = paytype;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public Date getOrderdate() {
		return this.orderdate;
	}

	public void setOrderdate(Date orderdate) {
		this.orderdate = orderdate;
	}

	public String getOrderid() {
		return this.orderid;
	}

	public void setOrderid(String orderid) {
		this.orderid = orderid;
	}

	public String getXfdemo() {
		return this.xfdemo;
	}

	public void setXfdemo(String xfdemo) {
		this.xfdemo = xfdemo;
	}

	public BigDecimal getOrderstatus() {
		return this.orderstatus;
	}

	public void setOrderstatus(BigDecimal orderstatus) {
		this.orderstatus = orderstatus;
	}

	public BigDecimal getCid() {
		return this.cid;
	}

	public void setCid(BigDecimal cid) {
		this.cid = cid;
	}

	public String getImei() {
		return this.imei;
	}

	public void setImei(String imei) {
		this.imei = imei;
	}

	public BigDecimal getYe() {
		return this.ye;
	}

	public void setYe(BigDecimal ye) {
		this.ye = ye;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public BigDecimal getCzje() {
		return this.czje;
	}

	public void setCzje(BigDecimal czje) {
		this.czje = czje;
	}

	public Serializable getConfiredate() {
		return this.confiredate;
	}

	public void setConfiredate(Serializable confiredate) {
		this.confiredate = confiredate;
	}

	public BigDecimal getTakeeffect() {
		return this.takeeffect;
	}

	public void setTakeeffect(BigDecimal takeeffect) {
		this.takeeffect = takeeffect;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getAlipaytradeno() {
		return this.alipaytradeno;
	}

	public void setAlipaytradeno(String alipaytradeno) {
		this.alipaytradeno = alipaytradeno;
	}

	public BigDecimal getPaytype() {
		return this.paytype;
	}

	public void setPaytype(BigDecimal paytype) {
		this.paytype = paytype;
	}

}
